import {test,expect,vi,beforeEach,afterEach} from 'vitest'
import {mount,flushPromises} from '@vue/test-utils'
import ContentPublisher from '../src/ContentPublisher.vue'
let wrapper,api
const preview=()=>({version:'pack-v1',locale:'zh-CN',contentSha256:'a'.repeat(64),previewHash:'b'.repeat(64),schemaVersion:4,questionCount:20,routeCount:4,chapterCount:3,versionState:'AVAILABLE'})
beforeEach(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});api={previewPack:vi.fn().mockResolvedValue(preview()),publishPack:vi.fn().mockResolvedValue({version:'pack-v1',locale:'zh-CN',contentSha256:'a'.repeat(64),created:true})};wrapper=mount(ContentPublisher,{props:{api}})})
afterEach(()=>{wrapper.unmount();vi.restoreAllMocks()})
async function file(file={name:'pack.json',size:20,text:async()=>'{}'}){Object.defineProperty(wrapper.find('input[type=file]').element,'files',{configurable:true,value:[file]});await wrapper.find('input[type=file]').trigger('change');await flushPromises()}
async function fill(){await wrapper.find('input[maxlength="80"]').setValue('pack-v1');await wrapper.find('textarea').setValue('Assistant text review');await file()}
async function check(){await fill();await wrapper.find('form').trigger('submit');await flushPromises()}
const publish=()=>wrapper.findAll('button').find(b=>b.text().includes('确认发布'))
test('local file selection does not upload; preview is deliberate and read-only',async()=>{await fill();expect(api.previewPack).not.toHaveBeenCalled();expect(api.publishPack).not.toHaveBeenCalled();await wrapper.find('form').trigger('submit');await flushPromises();expect(api.previewPack).toHaveBeenCalledTimes(1);expect(wrapper.text()).toContain('20');expect(publish().attributes('disabled')).toBeDefined();expect(api.publishPack).not.toHaveBeenCalled()})
test('publication requires explicit confirmation and preserves preview hash',async()=>{await check();await wrapper.find('input[type=checkbox]').setValue(true);await publish().trigger('click');await flushPromises();expect(api.publishPack.mock.calls[0][0]).toEqual({version:'pack-v1',locale:'zh-CN',document:'{}',reason:'Assistant text review',previewHash:'b'.repeat(64)});expect(wrapper.find('[role=status]').text()).toContain('一并保存')})
test('changing version, locale, review reason or file invalidates preview',async()=>{for(const selector of ['input[maxlength="80"]','select','textarea']){await check();await wrapper.find(selector).setValue(selector==='select'?'en':'changed');expect(wrapper.find('.preview').exists()).toBe(false)}await check();await file({name:'new.json',size:2,text:async()=>'[]'});expect(wrapper.find('.preview').exists()).toBe(false)})
test('oversized file is rejected before reading or sending',async()=>{const read=vi.fn();await file({name:'large.json',size:262145,text:read});expect(read).not.toHaveBeenCalled();expect(api.previewPack).not.toHaveBeenCalled();expect(wrapper.find('[role=alert]').text()).toContain('256')})
test('permission and version conflicts remain visible without a success state',async()=>{for(const code of ['CONTENT_PUBLICATION_FORBIDDEN','PACK_VERSION_CONFLICT','CONTENT_PUBLICATION_NOT_CONFIGURED']){api.previewPack.mockRejectedValueOnce({code});await fill();await wrapper.find('form').trigger('submit');await flushPromises();expect(wrapper.find('[role=alert]').exists()).toBe(true);expect(wrapper.find('.preview').exists()).toBe(false);expect(wrapper.find('[role=status]').exists()).toBe(false)}})
test('edit aborts a pending preview and late result cannot restore it',async()=>{let finish;api.previewPack.mockReturnValue(new Promise(r=>finish=r));await fill();await wrapper.find('form').trigger('submit');const signal=api.previewPack.mock.calls[0][1];await wrapper.find('textarea').setValue('new review');expect(signal.aborted).toBe(true);finish(preview());await flushPromises();expect(wrapper.find('.preview').exists()).toBe(false)})
test('unmount aborts publication and ignores late completion',async()=>{await check();let finish;api.publishPack.mockReturnValue(new Promise(r=>finish=r));await wrapper.find('input[type=checkbox]').setValue(true);await publish().trigger('click');const signal=api.publishPack.mock.calls[0][1];wrapper.unmount();expect(signal.aborted).toBe(true);finish({created:true});await flushPromises()})
test('hidden tab requires fresh preview and pagehide clears uploaded content',async()=>{await check();Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));await flushPromises();expect(wrapper.find('.preview').exists()).toBe(false);window.dispatchEvent(new Event('pagehide'));await flushPromises();expect(wrapper.text()).not.toContain('pack.json');expect(wrapper.find('button').attributes('disabled')).toBeDefined()})
test('malformed or mismatched preview never enables confirmation',async()=>{api.previewPack.mockResolvedValue({...preview(),version:'other-version'});await check();expect(wrapper.find('.preview').exists()).toBe(false);expect(api.publishPack).not.toHaveBeenCalled()})
test('lost publish response clears preview and retries require fresh confirmation',async()=>{await check();api.publishPack.mockRejectedValueOnce({code:'NETWORK_ERROR'});await wrapper.find('input[type=checkbox]').setValue(true);await publish().trigger('click');await flushPromises();expect(wrapper.find('.preview').exists()).toBe(false);expect(wrapper.find('[role=status]').exists()).toBe(false);await wrapper.find('form').trigger('submit');await flushPromises();expect(publish().attributes('disabled')).toBeDefined()})
test('invalid publication receipt cannot fabricate a saved state',async()=>{await check();api.publishPack.mockResolvedValue({created:true,version:'other'});await wrapper.find('input[type=checkbox]').setValue(true);await publish().trigger('click');await flushPromises();expect(wrapper.find('[role=status]').exists()).toBe(false);expect(wrapper.find('[role=alert]').exists()).toBe(true)})
