import {test,expect,vi,afterEach} from 'vitest'
import {mount,flushPromises} from '@vue/test-utils'
import JourneyPicker from '../src/JourneyPicker.vue'
let wrapper
const fresh=()=>({version:'v4',locale:'en',campaignId:'world',campaignVersion:'r1',title:'Journey',definitionHash:'a'.repeat(64),levels:[1,2,3].map(n=>({id:'chapter-'+n,title:'Chapter '+n,index:n,requiredCorrect:n===3?4:3,slots:Array.from({length:5},()=>({category:'space',difficulty:n})),unlocked:n===1,passed:false,attempts:0,bestScore:0,bestCorrect:0}))})
afterEach(()=>{wrapper?.unmount();Object.defineProperty(document,'hidden',{configurable:true,value:false})})
async function setup(api){wrapper=mount(JourneyPicker,{props:{api,locale:'en',disabled:false}});await flushPromises()}
test('three actual stages show pass targets and locked buttons never emit play',async()=>{await setup({journey:vi.fn().mockResolvedValue(fresh())});const buttons=wrapper.findAll('.journey-path button');expect(buttons).toHaveLength(3);expect(buttons[1].attributes('disabled')).toBeDefined();await buttons[1].trigger('click');expect(wrapper.emitted('play')).toBeUndefined();await buttons[0].trigger('click');expect(wrapper.emitted('play').at(-1)).toEqual([{chapterId:'chapter-1',version:'v4'}]);expect(wrapper.text()).toContain('at least 3')})
test('failed reads do not display zeroed progress or invented unlocks',async()=>{await setup({journey:vi.fn().mockRejectedValue(new Error())});expect(wrapper.find('.journey-path').exists()).toBe(false);expect(wrapper.find('[role=alert]').exists()).toBe(true)})
test('identity expiry is forwarded with no old map retained',async()=>{const api={journey:vi.fn().mockResolvedValueOnce(fresh()).mockRejectedValueOnce({status:401})};await setup(api);await wrapper.find('button').trigger('click');await flushPromises();expect(wrapper.emitted('expired')).toHaveLength(1);expect(wrapper.find('.journey-path').exists()).toBe(false)})
test('hidden map clears progress and visible state waits for a fresh response',async()=>{let resolve;const api={journey:vi.fn().mockResolvedValueOnce(fresh()).mockReturnValueOnce(new Promise(r=>resolve=r))};await setup(api);Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));await flushPromises();expect(wrapper.find('.journey-path').exists()).toBe(false);Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));await flushPromises();expect(wrapper.find('.journey-path').exists()).toBe(false);resolve(fresh());await flushPromises();expect(wrapper.find('.journey-path').exists()).toBe(true)})
test('language switch and unmount invalidate pending results',async()=>{let resolve,signal;await setup({journey:vi.fn((_l,s)=>{signal=s;return new Promise(r=>resolve=r)})});await wrapper.setProps({locale:'zh-CN'});resolve(fresh());await flushPromises();expect(wrapper.find('.journey-path').exists()).toBe(false);wrapper.unmount();expect(signal.aborted).toBe(true)})
