import test from 'node:test'
import assert from 'node:assert/strict'
import {validateJourney,validateChapter} from '../src/journey.js'
const fresh=()=>({version:'v4',locale:'en',campaignId:'world',campaignVersion:'r1',title:'Journey',definitionHash:'a'.repeat(64),levels:[1,2,3].map((n)=>({id:'chapter-'+n,title:'Chapter '+n,index:n,requiredCorrect:n===3?4:3,slots:Array.from({length:5},()=>({category:'space',difficulty:n})),unlocked:n===1,passed:false,attempts:0,bestScore:0,bestCorrect:0}))})
test('initial three-chapter map exposes only the first unlock and immutable metadata',()=>{const v=validateJourney(fresh(),'en');assert.equal(v.levels.filter(l=>l.unlocked).length,1);assert.ok(Object.isFrozen(v.levels[0].slots));assert.throws(()=>validateJourney(v,'zh-CN'))})
test('future unlock cannot be manufactured without earlier passed chapters',()=>{const v=fresh();v.levels[1].unlocked=true;assert.throws(()=>validateJourney(v,'en'))})
test('best correct pass flags attempts and difficulty must agree',()=>{for(const mutate of [v=>v.levels[0].bestCorrect=4,v=>v.levels[0].attempts=-1,v=>v.levels[1].slots=v.levels[0].slots,v=>v.levels[0].siteId=1]){const v=fresh();mutate(v);assert.throws(()=>validateJourney(v,'en'))}})
test('completed first chapter unlocks second while third remains closed',()=>{const v=fresh();Object.assign(v.levels[0],{passed:true,attempts:2,bestCorrect:3,bestScore:375});v.levels[1].unlocked=true;assert.equal(validateJourney(v,'en').levels[1].unlocked,true)})
test('old packs can return no journey but never invented chapter progress',()=>{const v={version:'v3',locale:'en',campaignId:null,campaignVersion:null,title:null,definitionHash:null,levels:[]};assert.deepEqual(validateJourney(v,'en').levels,[]);v.levels=fresh().levels;assert.throws(()=>validateJourney(v,'en'))})
test('persisted chapter metadata requires exact predecessor count and scope-free shape',()=>{const c={campaignId:'world',campaignVersion:'r1',definitionHash:'a'.repeat(64),title:'Journey',levelId:'two',levelTitle:'Two',index:2,total:3,requiredCorrect:3,priorLevelIds:['one']};assert.equal(validateChapter(c).index,2);assert.throws(()=>validateChapter({...c,priorLevelIds:[]}));assert.throws(()=>validateChapter({...c,userId:7}));assert.throws(()=>validateChapter({...c,levelId:'free'}))})
