import test from 'node:test'
import assert from 'node:assert/strict'
import {webcrypto} from 'node:crypto'
import {createNarrationPlayer} from '../src/narration.js'
const sid='00000000-0000-0000-0000-000000000001',rid='00000000-0000-0000-0000-000000000002'
const s={sessionId:sid,roundId:rid,phase:'LOADING',loadingDeadline:15000}
const wave=new Uint8Array(32044),hash=Buffer.from(await webcrypto.subtle.digest('SHA-256',wave)).toString('hex')
const meta=()=>({available:true,sessionId:sid,roundId:rid,sha256:hash,durationMillis:1000,readingMillis:3000,byteLength:wave.length,contentType:'audio/wav',serverNow:1000,expiresAt:15000})
function setup({metadata=meta(),fetcher,Context,timeoutMs=100}={}){const states=[];class Audio{constructor(){this.currentTime=0;this.destination={};this.state={closed:0,started:0,stopped:0};states.push(this.state)}async resume(){}async close(){this.state.closed++}async decodeAudioData(){return {duration:1,numberOfChannels:1}}createBufferSource(){return{connect(){},start:()=>this.state.started++,stop:()=>this.state.stopped++}}}let requests=0;const player=createNarrationPlayer({Context:Context||Audio,timeoutMs,digest:b=>webcrypto.subtle.digest('SHA-256',b),fetcher:fetcher||((url,options)=>{requests++;assert.equal(url,`/api/quiz/sessions/${sid}/rounds/${rid}/narration/audio`);assert.equal(options.redirect,'error');assert.equal(options.credentials,'same-origin');return Promise.resolve(new Response(wave,{headers:{'Content-Type':'audio/wav','Content-Length':String(wave.length)}}))})});return{player,states,requests:()=>requests,api:{narration:async()=>metadata}}}
const reading={...s,phase:'READING',serverNow:2000,opensAt:5000,deadline:25000}
test('verified same-origin clip preloads then plays only in matching reading window',async()=>{const x=setup();assert.equal(await x.player.prepare(x.api,s),true);assert.equal(x.states[0].started,0);assert.equal(x.player.play(reading,2100),true);assert.equal(x.states[0].started,1);x.player.cancel();assert.equal(x.states[0].closed,1)})
test('missing narration keeps text flow without fetching bytes',async()=>{const x=setup({metadata:{available:false,sessionId:sid,roundId:rid}});assert.equal(await x.player.prepare(x.api,s),false);assert.equal(x.requests(),0);assert.equal(x.states[0].closed,1)})
test('metadata wrong scope extra answer and changed loading deadline are rejected',async()=>{for(const patch of [{sessionId:rid},{roundId:sid},{answer:2},{expiresAt:16000},{contentType:'audio/mpeg'},{byteLength:9999999},{sha256:'x'}]){const x=setup({metadata:{...meta(),...patch}});assert.equal(await x.player.prepare(x.api,s),false);assert.equal(x.requests(),0)}})
test('hash mismatch and missing content length never decode or play',async()=>{for(const response of [()=>new Response(new Uint8Array(32044).fill(1),{headers:{'Content-Type':'audio/wav','Content-Length':'32044'}}),()=>new Response(wave,{headers:{'Content-Type':'audio/wav'}})]){const x=setup({fetcher:async()=>response()});assert.equal(await x.player.prepare(x.api,s),false);assert.equal(x.states[0].started,0)}})
test('late or different round playback is refused',async()=>{const x=setup();await x.player.prepare(x.api,s);assert.equal(x.player.play({...reading,roundId:sid},2100),false);assert.equal(x.player.play({...reading,phase:'ANSWERING'},5100),false);assert.equal(x.player.play(reading,5100),false);x.player.cancel()})
test('bounded setup closes an unresponsive dependency',async()=>{const x=setup({timeoutMs:10});x.api.narration=()=>new Promise(()=>{});assert.equal(await x.player.prepare(x.api,s),false);assert.equal(x.states[0].closed,1)})
test('cancellation before metadata ignores late data and avoids byte request',async()=>{let resolve;const x=setup();x.api.narration=()=>new Promise(r=>resolve=r);const pending=x.player.prepare(x.api,s);await new Promise(r=>setImmediate(r));x.player.cancel();resolve(meta());assert.equal(await pending,false);assert.equal(x.requests(),0);assert.equal(x.states[0].closed,1)})
test('constructor denial remains text-only',async()=>{const x=setup({Context:class{constructor(){throw Error('denied')}}});assert.equal(await x.player.prepare(x.api,s),false)})
