import {test,expect,vi,beforeEach,afterEach} from 'vitest'
import {mount,flushPromises} from '@vue/test-utils'
import PlayerRecord from '../src/PlayerRecord.vue'
import {QuizApiError} from '../src/server-api.js'
const sid='00000000-0000-0000-0000-000000000001'
const empty=()=>({progress:{gamesPlayed:0,bestScore:0,totalScore:0,correctAnswers:0,bestStreak:0},recent:[],limit:20})
const full=()=>({progress:{gamesPlayed:1,bestScore:750,totalScore:750,correctAnswers:5,bestStreak:5},recent:[{sessionId:sid,locale:'en',score:750,correctAnswers:5,bestStreak:5,completedAt:1791000000000}],limit:20})
let wrapper,api
beforeEach(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});sessionStorage.clear();localStorage.clear();api={record:vi.fn().mockResolvedValue(full())}})
afterEach(()=>{wrapper?.unmount();wrapper=null;document.body.innerHTML='';vi.restoreAllMocks()})
async function show(){wrapper=mount(PlayerRecord,{props:{api,locale:'zh-CN'},attachTo:document.body});await flushPromises()}
async function button(text){await wrapper.findAll('button').find(b=>b.text().includes(text)).trigger('click');await flushPromises()}
test('shows authoritative personal statistics and completed game without identifiers or storage',async()=>{await show();expect(wrapper.text()).toContain('750');expect(wrapper.findAll('.record-list li')).toHaveLength(1);expect(wrapper.text()).not.toContain(sid);expect(sessionStorage.length).toBe(0);expect(localStorage.length).toBe(0);expect(document.activeElement.id).toBe('record-title')})
test('empty state is explicit only after successful zero response',async()=>{api.record.mockResolvedValue(empty());await show();expect(wrapper.text()).toContain('完成第一场挑战');expect(wrapper.findAll('.record-list li')).toHaveLength(0)})
test('network error shows no zero or stale scores and retry loads server data',async()=>{api.record.mockRejectedValueOnce(new QuizApiError('NETWORK_ERROR'));await show();expect(wrapper.find('[role="alert"]').exists()).toBe(true);expect(wrapper.find('.record-totals').exists()).toBe(false);await button('重试');expect(wrapper.find('.record-totals').exists()).toBe(true);expect(api.record).toHaveBeenCalledTimes(2)})
test('refresh clears previous account data while waiting',async()=>{await show();let resolve;api.record.mockReturnValue(new Promise(r=>resolve=r));await button('更新战绩');expect(wrapper.find('.record-totals').exists()).toBe(false);expect(wrapper.text()).toContain('正在读取');resolve(empty());await flushPromises();expect(wrapper.find('.record-empty').exists()).toBe(true);expect(wrapper.findAll('.record-list li')).toHaveLength(0);expect(wrapper.find('.record-totals dd').text()).toMatch(/^0/)})
test('401 and 403 clear all data and notify parent instead of retrying',async()=>{for(const status of [401,403]){api.record.mockRejectedValueOnce(new QuizApiError('AUTHENTICATION_REQUIRED',status));await show();expect(wrapper.emitted('expired')[0][0].status).toBe(status);expect(wrapper.find('.record-totals').exists()).toBe(false);wrapper.unmount()}})
test('invalid server data cannot appear as a personal record',async()=>{api.record.mockResolvedValue({...full(),token:'unexpected'});await show();expect(wrapper.find('[role="alert"]').exists()).toBe(true);expect(wrapper.find('.record-totals').exists()).toBe(false)})
test('close aborts the pending request and ignores late completion',async()=>{let resolve;api.record.mockReturnValue(new Promise(r=>resolve=r));await show();const signal=api.record.mock.calls[0][0];await button('收起');expect(signal.aborted).toBe(true);resolve(full());await flushPromises();expect(wrapper.emitted('close')).toHaveLength(1);expect(wrapper.find('.record-totals').exists()).toBe(false)})
test('late auth failure after unmount does not affect a new screen',async()=>{let reject;api.record.mockReturnValue(new Promise((_r,j)=>reject=j));await show();wrapper.unmount();reject(new QuizApiError('AUTHENTICATION_REQUIRED',401));await flushPromises();expect(wrapper.emitted('expired')).toBeUndefined()})
test('tab hiding clears and cancels; becoming visible reloads fresh identity',async()=>{await show();Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));await flushPromises();expect(wrapper.find('.record-totals').exists()).toBe(false);api.record.mockResolvedValue(empty());Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));await flushPromises();expect(wrapper.text()).toContain('完成第一场挑战');expect(api.record).toHaveBeenCalledTimes(2)})
test('escape provides an accessible close action',async()=>{await show();await wrapper.find('section').trigger('keydown',{key:'Escape'});expect(wrapper.emitted('close')).toHaveLength(1)})
test('English locale formats headings and empty guidance',async()=>{api.record.mockResolvedValue(empty());wrapper=mount(PlayerRecord,{props:{api,locale:'en'}});await flushPromises();expect(wrapper.text()).toContain('Your challenge record');expect(wrapper.text()).toContain('Finish your first challenge')})
