import {test,expect,vi,beforeEach,afterEach} from 'vitest'
import {mount,flushPromises} from '@vue/test-utils'
import ServerApp from '../src/ServerApp.vue'
import {QuizApiError} from '../src/server-api.js'
const api=vi.hoisted(()=>Object.fromEntries(['challenges','create','current','ready','answer','next','fifty','abandon','record'].map(k=>[k,vi.fn()])))
vi.mock('../src/server-api',async importOriginal=>({...await importOriginal(),createQuizApi:()=>api}))
vi.mock('../src/audio',()=>({createStudioAudio:()=>({enable:vi.fn().mockResolvedValue(),cue:vi.fn(),close:vi.fn()})}))
const narration=vi.hoisted(()=>({arm:vi.fn(),prepare:vi.fn(),play:vi.fn(),cancel:vi.fn()}))
vi.mock('../src/narration',()=>({createNarrationPlayer:()=>narration}))
const sid='00000000-0000-0000-0000-000000000001',rid='00000000-0000-0000-0000-000000000002',now=1790985600000
const snap=(patch={})=>{const value={sessionId:sid,roundId:rid,roundNumber:1,phase:'LOADING',locale:'zh-CN',revision:1,serverNow:now,opensAt:0,deadline:0,loadingDeadline:now+15000,score:0,streak:0,lifelineUsed:false,question:'由服务器提供的问题',options:['甲','乙','丙','丁'],eliminated:[],reveal:null,...patch};if(['LOADING','ABANDONED'].includes(value.phase))Object.assign(value,{question:null,options:[],eliminated:[],reveal:null});return value}
const active=()=>snap({phase:'ANSWERING',revision:2,opensAt:now,deadline:now+20000})
const result=()=>snap({...active(),phase:'REVEALING',revision:3,score:100,streak:1,reveal:{roundId:rid,correct:0,selected:0,awarded:100,explanation:'服务器审核解释'}})
let wrapper
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(now);vi.stubGlobal('matchMedia',()=>({matches:false}));sessionStorage.clear();for(const fn of Object.values(narration))fn.mockReset();narration.arm.mockReturnValue(true);narration.prepare.mockResolvedValue(true);narration.play.mockReturnValue(true);for(const fn of Object.values(api))fn.mockReset();api.record.mockResolvedValue({progress:{gamesPlayed:0,bestScore:0,totalScore:0,correctAnswers:0,bestStreak:0},recent:[],limit:20});api.create.mockResolvedValue(snap());api.current.mockResolvedValue(active());api.ready.mockResolvedValue(active());api.answer.mockResolvedValue({session:result(),accepted:true});wrapper=mount(ServerApp,{attachTo:document.body})})
afterEach(()=>{wrapper?.unmount();document.body.innerHTML='';vi.useRealTimers();vi.unstubAllGlobals()})
async function click(text){const b=wrapper.findAll('button').find(b=>b.text().includes(text));expect(b).toBeTruthy();await b.trigger('click');await flushPromises()}
async function enter(){await click('连接并开局');await click('准备好了')}
test('server entry fails closed with no fabricated question when identity is absent',async()=>{api.create.mockRejectedValue(new QuizApiError('IDENTITY_ADAPTER_NOT_CONFIGURED',503));await click('连接并开局');expect(wrapper.text()).toContain('现有登录服务尚未接入');expect(wrapper.find('.answers').exists()).toBe(false);expect(wrapper.find('.score-label').exists()).toBe(false)})
test('ready answer and next use only canonical server snapshots',async()=>{await enter();expect(api.ready).toHaveBeenCalledWith(sid,rid);await wrapper.findAll('.answers button')[0].trigger('click');await flushPromises();expect(wrapper.find('.score-label').text()).toContain('100');expect(wrapper.find('.reveal').text()).toContain('服务器审核解释');api.next.mockResolvedValue(snap({roundNumber:2,revision:4,roundId:'00000000-0000-0000-0000-000000000003',score:100}));await click('下一道挑战');expect(wrapper.find('.question-meta').text()).toContain('02');expect(api.next).toHaveBeenCalledWith(sid,rid)})
test('duplicate clicks lock while answer is pending and no optimistic score appears',async()=>{await enter();let resolve;api.answer.mockReturnValue(new Promise(r=>resolve=r));await wrapper.findAll('.answers button')[0].trigger('click');await wrapper.findAll('.answers button')[1].trigger('click');expect(api.answer).toHaveBeenCalledTimes(1);expect(wrapper.find('.score-label').text()).toContain('0');resolve({session:result()});await flushPromises();expect(wrapper.find('.score-label').text()).toContain('100')})
test('network retry sends identical answer idempotency key',async()=>{await enter();api.answer.mockRejectedValueOnce(new QuizApiError('NETWORK_ERROR'));await wrapper.findAll('.answers button')[0].trigger('click');await flushPromises();const first=api.answer.mock.calls[0];await click('重试同一请求');expect(api.answer.mock.calls[1]).toEqual(first);expect(wrapper.find('.reveal').exists()).toBe(true)})
test('create retry preserves language and idempotency key',async()=>{api.create.mockRejectedValueOnce(new QuizApiError('REQUEST_TIMEOUT'));await click('连接并开局');const first=api.create.mock.calls[0];await click('重试同一请求');expect(api.create.mock.calls[1]).toEqual(first);expect(wrapper.find('.server-ready').exists()).toBe(true)})
test('lower-revision poll cannot replace result or unlock another answer',async()=>{await enter();await wrapper.findAll('.answers button')[0].trigger('click');await flushPromises();api.current.mockResolvedValue(active());vi.advanceTimersByTime(1100);await flushPromises();expect(wrapper.find('.reveal').exists()).toBe(true);expect(wrapper.find('.score-label').text()).toContain('100')})
test('server deadline projection disables controls without manufacturing a result',async()=>{await enter();api.current.mockReturnValue(new Promise(()=>{}));vi.advanceTimersByTime(21000);await flushPromises();expect(wrapper.text()).toContain('等待服务器同步结果');expect(wrapper.find('.reveal').exists()).toBe(false);expect(api.answer).not.toHaveBeenCalled();expect(wrapper.find('.answers button').attributes('disabled')).toBeDefined()})
test('expired authentication immediately hides the old question and score',async()=>{await enter();api.current.mockRejectedValue(new QuizApiError('AUTHENTICATION_REQUIRED',401));await click('同步');expect(wrapper.text()).toContain('登录已失效');expect(wrapper.find('.answers').exists()).toBe(false);expect(wrapper.text()).not.toContain('由服务器提供的问题')})
test('resumption stores only opaque session hint and never a token or score',async()=>{await enter();expect(JSON.parse(sessionStorage.getItem('quiz.server.session.v1'))).toEqual({sessionId:sid,locale:'zh-CN'});wrapper.unmount();wrapper=mount(ServerApp);await flushPromises();expect(api.current).toHaveBeenCalledWith(sid);expect(wrapper.find('.answers').exists()).toBe(true)})
test('foreign session response is refused',async()=>{await enter();api.answer.mockResolvedValue({session:{...result(),sessionId:rid}});await wrapper.findAll('.answers button')[0].trigger('click');await flushPromises();expect(wrapper.text()).toContain('INVALID_SESSION_SNAPSHOT');expect(wrapper.find('.score-label').text()).toContain('0')})
test('keyboard uses same command and lifeline elimination remains server controlled',async()=>{await enter();api.fifty.mockResolvedValue(snap({...active(),revision:3,lifelineUsed:true,eliminated:[2,3]}));await click('50:50');expect(wrapper.findAll('.answers .eliminated')).toHaveLength(2);window.dispatchEvent(new KeyboardEvent('keydown',{key:'C'}));await flushPromises();expect(api.answer).not.toHaveBeenCalled();window.dispatchEvent(new KeyboardEvent('keydown',{key:'A'}));await flushPromises();expect(api.answer).toHaveBeenCalledTimes(1)})
test('late request after unmount does not write a resumable hint',async()=>{let resolve;api.create.mockReturnValue(new Promise(r=>resolve=r));await wrapper.find('.start-button').trigger('click');wrapper.unmount();resolve(snap());await flushPromises();expect(sessionStorage.getItem('quiz.server.session.v1')).toBeNull();wrapper=null})
test('sync recovers an uncertain accepted answer without submitting again',async()=>{await enter();api.answer.mockRejectedValueOnce(new QuizApiError('NETWORK_ERROR'));await wrapper.findAll('.answers button')[0].trigger('click');await flushPromises();api.current.mockResolvedValue(result());await click('同步服务器');expect(wrapper.find('.server-alert').exists()).toBe(false);expect(wrapper.find('.reveal').exists()).toBe(true);expect(api.answer).toHaveBeenCalledTimes(1)})

test('sound-enabled readiness preloads then plays only the accepted server reading snapshot',async()=>{api.ready.mockResolvedValue(snap({phase:'READING',revision:2,opensAt:now+3000,deadline:now+23000}));await click('声音关');await enter();expect(narration.prepare).toHaveBeenCalledWith(api,expect.objectContaining({phase:'READING'}));expect(narration.play).toHaveBeenCalledWith(expect.objectContaining({phase:'READING'}),expect.any(Number));expect(wrapper.text()).toContain('已审核旁白');expect(api.answer).not.toHaveBeenCalled();await click('声音开');expect(narration.cancel).toHaveBeenCalled()})
test('missing optional narration leaves authoritative ready and text usable',async()=>{narration.prepare.mockResolvedValue(false);await click('声音关');await enter();expect(api.ready).toHaveBeenCalledTimes(1);expect(narration.play).not.toHaveBeenCalled();expect(wrapper.text()).toContain('旁白不可用');expect(wrapper.find('.answers').exists()).toBe(true)})
test('unmount during post-Ready audio preparation cannot play or change state',async()=>{let resolve;narration.prepare.mockReturnValue(new Promise(r=>resolve=r));api.ready.mockResolvedValue(snap({phase:'READING',revision:2,opensAt:now+3000,deadline:now+23000}));await click('声音关');await click('连接并开局');await wrapper.find('.server-ready button').trigger('click');wrapper.unmount();resolve(true);await flushPromises();expect(api.ready).toHaveBeenCalledTimes(1);expect(narration.play).not.toHaveBeenCalled();expect(narration.cancel).toHaveBeenCalled();wrapper=null})

test('record entry fetches only on request and closing restores keyboard focus',async()=>{expect(api.record).not.toHaveBeenCalled();await click('查看我的战绩');expect(wrapper.find('.player-record').exists()).toBe(true);expect(api.record).toHaveBeenCalledTimes(1);await click('收起');expect(wrapper.find('.player-record').exists()).toBe(false);expect(document.activeElement.classList.contains('record-open')).toBe(true);await click('查看我的战绩');expect(api.record).toHaveBeenCalledTimes(2)})
test('starting a challenge closes the record and ignores an obsolete auth failure',async()=>{let reject;api.record.mockReturnValue(new Promise((_r,j)=>reject=j));await click('查看我的战绩');const signal=api.record.mock.calls[0][0];await click('连接并开局');expect(signal.aborted).toBe(true);expect(wrapper.find('.player-record').exists()).toBe(false);reject(new QuizApiError('AUTHENTICATION_REQUIRED',401));await flushPromises();expect(wrapper.find('.server-ready').exists()).toBe(true);expect(wrapper.find('.server-alert').exists()).toBe(false);expect(wrapper.find('.record-open').exists()).toBe(false)})
test('record authentication expiry clears finished-session scores and returns to sign-in guidance',async()=>{api.create.mockResolvedValue(snap({...result(),phase:'FINISHED',roundNumber:5}));await click('连接并开局');expect(wrapper.find('.finale').exists()).toBe(true);api.record.mockRejectedValue(new QuizApiError('AUTHENTICATION_REQUIRED',401));await click('查看我的战绩');expect(wrapper.find('.finale').exists()).toBe(false);expect(wrapper.find('.player-record').exists()).toBe(false);expect(wrapper.text()).toContain('登录已失效');expect(sessionStorage.getItem('quiz.server.session.v1')).toBeNull()})

test.each([401,403,404])('a pending successful poll cannot revive a session after command denial %s',async status=>{await enter();let resolveOld;api.current.mockReturnValueOnce(new Promise(r=>resolveOld=r));await click('同步');api.answer.mockRejectedValueOnce(new QuizApiError('AUTHENTICATION_REQUIRED',status));await wrapper.findAll('.answers button')[0].trigger('click');await flushPromises();expect(wrapper.find('.answers').exists()).toBe(false);resolveOld(active());await flushPromises();expect(wrapper.find('.answers').exists()).toBe(false);expect(wrapper.text()).not.toContain('由服务器提供的问题');expect(wrapper.find('.server-entry').exists()).toBe(true);if(status!==401)expect(sessionStorage.getItem('quiz.server.session.v1')).toBeNull()})
test('a successful answer already in flight cannot revive data after polling reports logout',async()=>{await enter();let rejectPoll,resolveAnswer;api.current.mockReturnValueOnce(new Promise((_r,j)=>rejectPoll=j));await click('同步');api.answer.mockReturnValueOnce(new Promise(r=>resolveAnswer=r));await wrapper.findAll('.answers button')[0].trigger('click');rejectPoll(new QuizApiError('AUTHENTICATION_REQUIRED',401));await flushPromises();resolveAnswer({session:result(),accepted:true});await flushPromises();expect(wrapper.find('.answers').exists()).toBe(false);expect(wrapper.find('.reveal').exists()).toBe(false);expect(wrapper.find('.score-label').exists()).toBe(false);expect(wrapper.find('.server-entry').exists()).toBe(true)})
test('after denial reconnect requires a fresh server response and old failure cannot replace it',async()=>{await enter();let rejectOld;api.current.mockReturnValueOnce(new Promise((_r,j)=>rejectOld=j));await click('同步');api.answer.mockRejectedValueOnce(new QuizApiError('AUTHENTICATION_REQUIRED',401));await wrapper.findAll('.answers button')[0].trigger('click');await flushPromises();api.current.mockResolvedValue(active());await click('重新连接');expect(api.current).toHaveBeenCalledWith(sid);expect(wrapper.find('.answers').exists()).toBe(true);rejectOld(new QuizApiError('AUTHENTICATION_REQUIRED',401));await flushPromises();expect(wrapper.find('.answers').exists()).toBe(true);expect(wrapper.find('.server-alert').exists()).toBe(false)})

test('obsolete narration preparation cannot play after a fresh authorized round',async()=>{await click('声音关');await click('连接并开局');api.ready.mockResolvedValue(snap({phase:'READING',revision:2,opensAt:now+3000,deadline:now+23000}));let oldPrepared;narration.prepare.mockReturnValueOnce(new Promise(r=>oldPrepared=r));await click('准备好了');api.current.mockRejectedValueOnce(new QuizApiError('AUTHENTICATION_REQUIRED',401));await click('同步');expect(wrapper.find('.server-entry').exists()).toBe(true);api.current.mockResolvedValue(active());await click('重新连接');oldPrepared(true);await flushPromises();expect(narration.play).not.toHaveBeenCalled();expect(wrapper.find('.answers').exists()).toBe(true)})

test('pagehide immediately conceals old session and pageshow requires a fresh response',async()=>{await enter();window.dispatchEvent(new Event('pagehide'));await flushPromises();expect(wrapper.find('.answers').exists()).toBe(false);expect(wrapper.element.hidden).toBe(true);let resolve;api.current.mockReturnValueOnce(new Promise(r=>resolve=r));const show=new Event('pageshow');Object.defineProperty(show,'persisted',{value:true});window.dispatchEvent(show);await flushPromises();expect(wrapper.find('.answers').exists()).toBe(false);expect(wrapper.element.hidden).toBe(false);resolve(active());await flushPromises();expect(wrapper.find('.answers').exists()).toBe(true)})
test('cached-page restore after logout never exposes old score or question',async()=>{await enter();window.dispatchEvent(new Event('pagehide'));await flushPromises();api.current.mockRejectedValueOnce(new QuizApiError('AUTHENTICATION_REQUIRED',401));const show=new Event('pageshow');Object.defineProperty(show,'persisted',{value:true});window.dispatchEvent(show);await flushPromises();expect(wrapper.find('.answers').exists()).toBe(false);expect(wrapper.find('.score-label').exists()).toBe(false);expect(wrapper.text()).toContain('登录已失效')})

test('a second pagehide invalidates an already scheduled cache restoration',async()=>{await enter();const calls=api.current.mock.calls.length;window.dispatchEvent(new Event('pagehide'));const show=new Event('pageshow');Object.defineProperty(show,'persisted',{value:true});window.dispatchEvent(show);window.dispatchEvent(new Event('pagehide'));await flushPromises();expect(wrapper.element.hidden).toBe(true);expect(wrapper.find('.answers').exists()).toBe(false);expect(api.current).toHaveBeenCalledTimes(calls)})
test('initial noncached pageshow does not duplicate the session request',async()=>{await enter();const calls=api.current.mock.calls.length;const show=new Event('pageshow');Object.defineProperty(show,'persisted',{value:false});window.dispatchEvent(show);await flushPromises();expect(api.current).toHaveBeenCalledTimes(calls);expect(wrapper.find('.answers').exists()).toBe(true)})
test('a cached page restored while hidden waits for visibility before fetching',async()=>{await enter();window.dispatchEvent(new Event('pagehide'));const calls=api.current.mock.calls.length;Object.defineProperty(document,'hidden',{configurable:true,value:true});const show=new Event('pageshow');Object.defineProperty(show,'persisted',{value:true});window.dispatchEvent(show);await flushPromises();expect(wrapper.element.hidden).toBe(true);expect(api.current).toHaveBeenCalledTimes(calls);Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));await flushPromises();expect(api.current).toHaveBeenCalledTimes(calls+1);expect(wrapper.find('.answers').exists()).toBe(true)})
test('post-reveal narration authentication denial clears the game immediately',async()=>{await click('声音关');api.ready.mockResolvedValue(snap({phase:'READING',revision:2,opensAt:now+3000,deadline:now+23000}));narration.prepare.mockRejectedValueOnce(new QuizApiError('AUTHENTICATION_REQUIRED',401));await enter();expect(wrapper.find('.answers').exists()).toBe(false);expect(wrapper.text()).toContain('登录已失效');expect(narration.play).not.toHaveBeenCalled()})

// Scenery follows accepted authority, never a pending click or an obsolete response.
test('stage outcome waits for the canonical answer and clears on authentication loss',async()=>{await enter();expect(wrapper.find('.server-scenery').attributes('data-tone')).toBe('answering');let resolve;api.answer.mockReturnValueOnce(new Promise(r=>resolve=r));await wrapper.findAll('.answers button')[0].trigger('click');await flushPromises();expect(wrapper.find('.server-scenery').attributes('data-tone')).toBe('answering');resolve({session:result()});await flushPromises();expect(wrapper.find('.server-scenery').attributes('data-tone')).toBe('correct');api.current.mockRejectedValueOnce(new QuizApiError('AUTHENTICATION_REQUIRED',401));await vi.advanceTimersByTimeAsync(1100);await flushPromises();expect(wrapper.find('.server-scenery').attributes('data-tone')).toBe('idle')})
test('live OS reduced motion preference updates stage and unregisters on exit',async()=>{wrapper.unmount();let change;const remove=vi.fn();vi.stubGlobal('matchMedia',()=>({matches:false,addEventListener:(_name,fn)=>{change=fn},removeEventListener:remove}));wrapper=mount(ServerApp);change({matches:true});await flushPromises();expect(wrapper.classes()).toContain('quiet-motion');expect(wrapper.find('.server-scenery').classes()).toContain('still-stage');change({matches:false});await flushPromises();expect(wrapper.classes()).not.toContain('quiet-motion');wrapper.unmount();expect(remove).toHaveBeenCalledWith('change',change);wrapper=null})

const routeCatalog=()=>({locale:'zh-CN',version:'routes-v3',plans:[{id:'rising',title:'测试进阶路线',slots:[1,1,2,2,3].map(difficulty=>({category:'space',difficulty}))}]})
test('selected route is bound to create and network retry keeps the exact selection',async()=>{api.challenges.mockResolvedValue(routeCatalog());await click('查看审核路线');await wrapper.findAll('.challenge-picker input')[1].setValue();api.create.mockRejectedValueOnce(new QuizApiError('REQUEST_TIMEOUT'));await click('连接并开局');const args=api.create.mock.calls[0];expect(args[2]).toEqual({id:'rising',version:'routes-v3'});await click('重试同一请求');expect(api.create.mock.calls[1]).toEqual(args)})
test('stale route failure requires explicit refresh or free choice without fallback start',async()=>{api.challenges.mockResolvedValue(routeCatalog());await click('查看审核路线');await wrapper.findAll('.challenge-picker input')[1].setValue();api.create.mockRejectedValueOnce(new QuizApiError('CHALLENGE_CATALOG_CHANGED',409));await click('连接并开局');expect(wrapper.text()).toContain('路线版本已更新');expect(api.create).toHaveBeenCalledTimes(1);expect(wrapper.find('.answers').exists()).toBe(false);await wrapper.findAll('.challenge-picker input')[0].setValue();await click('连接并开局');expect(api.create.mock.calls[1]).toHaveLength(2)})
