import {test,expect,vi,beforeEach,afterEach} from 'vitest'
import {mount,flushPromises} from '@vue/test-utils'
import ServerApp from '../src/ServerApp.vue'
import {QuizApiError} from '../src/server-api.js'
const api=vi.hoisted(()=>Object.fromEntries(['create','current','ready','answer','next','fifty','abandon','voice','capabilities'].map(k=>[k,vi.fn()])))
const capture=vi.hoisted(()=>({start:vi.fn(),stop:vi.fn(),cancel:vi.fn(),hooks:null,created:vi.fn()}))
vi.mock('../src/server-api',async original=>({...await original(),createQuizApi:()=>api}))
vi.mock('../src/audio',()=>({createStudioAudio:()=>({enable:vi.fn().mockResolvedValue(),cue:vi.fn(),close:vi.fn()})}))
vi.mock('../src/voice-recorder',()=>({createVoiceRecorder:options=>{capture.hooks=options;capture.created();return capture}}))
const sid='00000000-0000-0000-0000-000000000001',rid='00000000-0000-0000-0000-000000000002',now=1790985600000
const snap=(patch={})=>({sessionId:sid,roundId:rid,roundNumber:1,phase:'LOADING',locale:'zh-CN',revision:1,serverNow:now,opensAt:0,deadline:0,loadingDeadline:now+15000,score:0,streak:0,lifelineUsed:false,question:'服务器问题',options:['甲','乙','丙','丁'],eliminated:[],reveal:null,...patch})
const active=()=>snap({phase:'ANSWERING',revision:2,opensAt:now,deadline:now+20000})
const candidate=(patch={})=>({sessionId:sid,roundId:rid,choice:1,transcript:'Option B',expiresAt:now+20000,serverNow:now+500,requiresConfirmation:true,...patch})
const caps=()=>({voiceCandidateConfigured:true,maxAudioMillis:6000,requiresConfirmation:true,processor:'same-host-private-asr',audioStored:false})
let wrapper
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(now);vi.stubGlobal('matchMedia',()=>({matches:false}));Object.defineProperty(document,'hidden',{configurable:true,value:false});sessionStorage.clear();for(const f of Object.values(api))f.mockReset();for(const name of ['start','stop','cancel','created'])capture[name].mockReset();capture.start.mockResolvedValue();capture.stop.mockReturnValue(new Uint8Array(3244));api.create.mockResolvedValue(snap());api.ready.mockResolvedValue(active());api.current.mockResolvedValue(active());api.capabilities.mockResolvedValue(caps());api.voice.mockResolvedValue(candidate());api.answer.mockImplementation(async(_s,_r,choice)=>({session:snap({...active(),phase:'REVEALING',revision:3,score:choice===1?100:0,reveal:{roundId:rid,correct:1,selected:choice,awarded:choice===1?100:0,explanation:'服务器判定'}})}));wrapper=mount(ServerApp,{attachTo:document.body})})
afterEach(()=>{wrapper?.unmount();document.body.innerHTML='';delete document.hidden;vi.useRealTimers();vi.unstubAllGlobals()})
async function click(text){const button=wrapper.findAll('button').find(b=>b.text().includes(text));expect(button).toBeTruthy();await button.trigger('click');await flushPromises()}
async function enter(){await click('连接并开局');await click('准备好了')}
async function start(){await wrapper.find('.voice-consent input').setValue(true);await click('按下开始录音')}
async function stop(){await click('结束并识别')}
test('microphone action is unavailable without explicit consent',async()=>{await enter();await click('按下开始录音');expect(api.capabilities).not.toHaveBeenCalled();expect(capture.created).not.toHaveBeenCalled()})
test('missing processor is rejected before microphone access',async()=>{await enter();api.capabilities.mockResolvedValue({...caps(),voiceCandidateConfigured:false});await start();expect(capture.created).not.toHaveBeenCalled();expect(wrapper.text()).toContain('没有打开麦克风')})
test('changed recipient or retention contract cannot start microphone',async()=>{await enter();api.capabilities.mockResolvedValue({...caps(),processor:'remote-cloud'});await start();expect(capture.created).not.toHaveBeenCalled();expect(wrapper.text()).toContain('隐私说明不一致')})
test('recognition only displays a candidate until explicit confirmation',async()=>{await enter();await start();await stop();expect(api.voice).toHaveBeenCalledTimes(1);expect(api.answer).not.toHaveBeenCalled();expect(wrapper.find('.score-label').text()).toContain('0');expect(wrapper.find('.voice-result').text()).toContain('Option B');await click('确认提交此答案');expect(api.answer.mock.calls[0][2]).toBe(1);expect(wrapper.find('.score-label').text()).toContain('100')})
test('user can correct the candidate and server remains the score authority',async()=>{await enter();await start();await stop();await wrapper.find('.voice-result select').setValue('2');await click('确认提交此答案');expect(api.answer.mock.calls[0][2]).toBe(2);expect(wrapper.find('.score-label').text()).toContain('0')})
test('ambiguous speech requires a manual selection before confirmation',async()=>{await enter();api.voice.mockResolvedValue(candidate({choice:null,transcript:'maybe'}));await start();await stop();expect(wrapper.find('.voice-confirm').attributes('disabled')).toBeDefined();expect(api.answer).not.toHaveBeenCalled();await wrapper.find('.voice-result select').setValue('0');await click('确认提交此答案');expect(api.answer.mock.calls[0][2]).toBe(0)})
test('a later recognition response cannot override a clicked answer',async()=>{await enter();let resolve;api.voice.mockReturnValue(new Promise(r=>resolve=r));await start();await stop();await wrapper.findAll('.answers button')[0].trigger('click');await flushPromises();resolve(candidate());await flushPromises();expect(api.answer).toHaveBeenCalledTimes(1);expect(wrapper.find('.voice-result').exists()).toBe(false)})
test('answer deadline cancels recording and never submits captured audio',async()=>{await enter();api.current.mockReturnValue(new Promise(()=>{}));await start();vi.advanceTimersByTime(21000);await flushPromises();expect(capture.cancel).toHaveBeenCalled();expect(api.voice).not.toHaveBeenCalled();expect(wrapper.find('.voice-stop').exists()).toBe(false)})
test('late microphone permission after unmount is cancelled',async()=>{await enter();let allow;capture.start.mockReturnValue(new Promise(r=>allow=r));await start();wrapper.unmount();wrapper=null;allow();await flushPromises();expect(capture.cancel).toHaveBeenCalled();expect(api.voice).not.toHaveBeenCalled()})
test('withdrawing consent stops input without uploading it',async()=>{await enter();await start();await wrapper.find('.voice-consent input').setValue(false);await flushPromises();expect(capture.cancel).toHaveBeenCalled();expect(api.voice).not.toHaveBeenCalled();expect(wrapper.find('.voice-start').attributes('disabled')).toBeDefined()})
test('hidden page cancels an active recording',async()=>{await enter();await start();Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));await flushPromises();expect(capture.cancel).toHaveBeenCalled();expect(api.voice).not.toHaveBeenCalled()})
test('identity expiry during recognition hides the previous question',async()=>{await enter();api.voice.mockRejectedValue(new QuizApiError('AUTHENTICATION_REQUIRED',401));await start();await stop();expect(wrapper.find('.answers').exists()).toBe(false);expect(wrapper.text()).toContain('登录已失效');expect(api.answer).not.toHaveBeenCalled()})
test('automatic duration limit and repeated stop cannot duplicate the upload',async()=>{await enter();let resolve;api.voice.mockReturnValue(new Promise(r=>resolve=r));await start();capture.hooks.onLimit();capture.hooks.onLimit();await flushPromises();expect(api.voice).toHaveBeenCalledTimes(1);resolve(candidate());await flushPromises();expect(api.answer).not.toHaveBeenCalled()})
test('three local attempts stop further microphone requests but still permit confirmation',async()=>{await enter();for(let i=0;i<3;i++){await start();await stop()}expect(api.voice).toHaveBeenCalledTimes(3);await click('按下开始录音');expect(capture.start).toHaveBeenCalledTimes(3);await click('确认提交此答案');expect(api.answer).toHaveBeenCalledTimes(1)})
test('permission denied and stale candidate are visible failures, never automatic answers',async()=>{await enter();capture.start.mockRejectedValueOnce({code:'MIC_PERMISSION_DENIED'});await start();expect(wrapper.text()).toContain('未获得麦克风许可');expect(api.voice).not.toHaveBeenCalled();api.voice.mockResolvedValue(candidate({roundId:sid}));await start();await stop();expect(wrapper.find('.voice-result').exists()).toBe(false);expect(api.answer).not.toHaveBeenCalled()})

test('recognition denial invalidates an older successful game poll and clears voice consent',async()=>{await enter();let resolvePoll;api.current.mockReturnValueOnce(new Promise(r=>resolvePoll=r));await click('同步');api.voice.mockRejectedValueOnce(new QuizApiError('AUTHENTICATION_REQUIRED',401));await start();await stop();resolvePoll(active());await flushPromises();expect(wrapper.find('.answers').exists()).toBe(false);expect(wrapper.find('.voice-result').exists()).toBe(false);api.current.mockResolvedValue(active());await click('重新连接');expect(wrapper.find('.voice-consent input').element.checked).toBe(false);expect(api.answer).not.toHaveBeenCalled()})

test('polling denial cancels an active microphone and old auto-stop cannot upload',async()=>{await enter();await start();const oldLimit=capture.hooks.onLimit;api.current.mockRejectedValueOnce(new QuizApiError('AUTHENTICATION_REQUIRED',401));await click('同步');expect(capture.cancel).toHaveBeenCalled();expect(wrapper.find('.voice-panel').exists()).toBe(false);oldLimit();await flushPromises();expect(api.voice).not.toHaveBeenCalled();expect(api.answer).not.toHaveBeenCalled()})
