import test from 'node:test'
import assert from 'node:assert/strict'
import {createQuizApi,QuizApiError} from '../src/server-api.js'
const sid='00000000-0000-0000-0000-000000000001',rid='00000000-0000-0000-0000-000000000002'
const success=data=>({ok:true,status:200,json:async()=>({version:1,mode:'server',requestId:'test',data,error:null})})
test('server transport sends only approved command fields and same-origin credentials',async()=>{let call;const api=createQuizApi({fetcher:async(...args)=>{call=args;return success({sessionId:sid})}});await api.create('en','stable-key');assert.equal(call[0],'/api/quiz/sessions');assert.equal(call[1].credentials,'same-origin');assert.deepEqual(JSON.parse(call[1].body),{locale:'en',idempotencyKey:'stable-key'});assert.deepEqual(Object.keys(call[1].headers),['Content-Type'])})
test('same explicit answer key produces identical retry payloads',async()=>{const calls=[];const api=createQuizApi({fetcher:async(...args)=>{calls.push(args);return success({accepted:true})}});await api.answer(sid,rid,2,'same-key');await api.answer(sid,rid,2,'same-key');assert.equal(calls[0][1].body,calls[1][1].body)})
test('ready and next have no fabricated body or identity headers',async()=>{const calls=[];const api=createQuizApi({fetcher:async(...args)=>{calls.push(args);return success({})}});await api.ready(sid,rid);await api.next(sid,rid);for(const [,options]of calls){assert.equal(options.method,'POST');assert.equal(options.body,undefined);assert.deepEqual(options.headers,{})}})
test('invalid IDs and history bounds never reach fetch',()=>{let called=false;const api=createQuizApi({fetcher:()=>{called=true}});assert.throws(()=>api.current('../private'));assert.throws(()=>api.archive(101));assert.throws(()=>api.archive(0));assert.equal(called,false)})
test('server-side error retains code and support request ID',async()=>{const api=createQuizApi({fetcher:async()=>({ok:false,status:409,json:async()=>({version:1,mode:'server',data:null,requestId:'req-test',error:{code:'ANSWER_DEADLINE_PASSED'}})})});await assert.rejects(()=>api.answer(sid,rid,2,'same-key'),e=>e instanceof QuizApiError&&e.code==='ANSWER_DEADLINE_PASSED'&&e.status===409&&e.requestId==='req-test'&&!e.retryable)})
test('network failure is explicitly retryable without inventing a result',async()=>{const api=createQuizApi({fetcher:async()=>{throw new Error('offline')}});await assert.rejects(()=>api.current(sid),e=>e.code==='NETWORK_ERROR'&&e.retryable)})
test('login HTML and wrong-mode payloads are rejected',async()=>{for(const response of[{ok:true,status:200,json:async()=>{throw new Error('html')}},{ok:true,status:200,json:async()=>({version:1,mode:'demo',data:{},error:null})},{ok:true,status:200,json:async()=>({version:1,mode:'server',data:{}})}]){const api=createQuizApi({fetcher:async()=>response});await assert.rejects(()=>api.current(sid),e=>e.code==='INVALID_API_RESPONSE')}})
