import test from 'node:test'
import assert from 'node:assert/strict'
import {validateRecord} from '../src/server-record.js'
import {createQuizApi} from '../src/server-api.js'
const sid='00000000-0000-0000-0000-000000000001'
const empty=()=>({progress:{gamesPlayed:0,bestScore:0,totalScore:0,correctAnswers:0,bestStreak:0},recent:[],limit:20})
const complete=()=>({progress:{gamesPlayed:1,bestScore:750,totalScore:750,correctAnswers:5,bestStreak:5},recent:[{sessionId:sid,locale:'en',score:750,correctAnswers:5,bestStreak:5,completedAt:1791000000000}],limit:20})
test('empty and fully completed server records validate without manufactured data',()=>{assert.equal(validateRecord(empty()).progress.gamesPlayed,0);const r=validateRecord(complete());assert.equal(r.recent[0].score,750);assert.ok(Object.isFrozen(r.progress));assert.ok(Object.isFrozen(r.recent[0]))})
test('invalid totals types limits and additional identity fields fail closed',()=>{for(const mutate of [r=>r.progress.gamesPlayed='1',r=>r.progress.totalScore=-1,r=>r.progress.bestScore=751,r=>r.progress.bestStreak=6,r=>r.progress.siteUserId=123,r=>r.limit=100,r=>r.token='secret',r=>r.progress.correctAnswers=6]){const r=complete();mutate(r);assert.throws(()=>validateRecord(r),/INVALID_PLAYER_RECORD/)}})
test('missing history and nonzero initial progress cannot be displayed',()=>{const r=complete();r.recent=[];assert.throws(()=>validateRecord(r));const e=empty();e.progress.totalScore=100;assert.throws(()=>validateRecord(e))})
test('duplicate and wrongly sorted completed games fail closed',()=>{const r=complete();r.progress.gamesPlayed=2;r.progress.totalScore=1500;r.progress.correctAnswers=10;r.recent.push({...r.recent[0]});assert.throws(()=>validateRecord(r));r.recent[1].sessionId='00000000-0000-0000-0000-000000000002';r.recent[1].completedAt++;assert.throws(()=>validateRecord(r))})
test('records with score or count totals that disagree with complete history are refused',()=>{for(const patch of [{totalScore:749},{correctAnswers:4}]){const r=complete();Object.assign(r.progress,patch);assert.throws(()=>validateRecord(r))}})
test('full history remains capped at twenty even for large aggregate counts',()=>{const r=complete();r.progress.gamesPlayed=30;r.progress.totalScore=22500;r.progress.correctAnswers=150;r.recent=Array.from({length:20},(_,i)=>({...r.recent[0],sessionId:`00000000-0000-0000-0000-${String(i+1).padStart(12,'0')}`,completedAt:r.recent[0].completedAt-i}));assert.equal(validateRecord(r).recent.length,20);r.recent.push({...r.recent[0]});assert.throws(()=>validateRecord(r))})
test('unsafe dates languages and detailed answer fields are rejected',()=>{for(const patch of [{completedAt:0},{completedAt:9007199254740991},{locale:'unknown'},{question:'private'},{sessionId:'bad'},{score:0}]){const r=complete();Object.assign(r.recent[0],patch);assert.throws(()=>validateRecord(r))}})
test('record transport is a single same-origin cancellable GET',async()=>{let seen;const api=createQuizApi({fetcher:async(url,options)=>{seen={url,options};return new Response(JSON.stringify({version:1,mode:'server',data:empty(),error:null}))}});validateRecord(await api.record());assert.equal(seen.url,'/api/quiz/me/record');assert.equal(seen.options.method,'GET');assert.equal(seen.options.credentials,'same-origin');assert.equal(seen.options.redirect,'error');assert.equal(seen.options.body,undefined)})
test('cancelling record transport rejects even a fetcher ignoring the signal',async()=>{const api=createQuizApi({fetcher:()=>new Promise(()=>{})});const controller=new AbortController();const pending=api.record(controller.signal);controller.abort();await assert.rejects(pending,/REQUEST_CANCELLED/)})
