import test from 'node:test'
import assert from 'node:assert/strict'
import {validateSnapshot,isNewer,commandResolved} from '../src/server-state.js'
const sid='00000000-0000-0000-0000-000000000001',rid='00000000-0000-0000-0000-000000000002'
const snapshot=()=>({sessionId:sid,roundId:rid,roundNumber:1,phase:'LOADING',locale:'en',revision:0,serverNow:100,opensAt:0,deadline:0,loadingDeadline:15100,score:0,streak:0,lifelineUsed:false,question:'Question?',options:['a','b','c','d'],eliminated:[],reveal:null})
test('server snapshot is bounded and immutable',()=>{const s=validateSnapshot(snapshot());assert.ok(Object.isFrozen(s));assert.ok(Object.isFrozen(s.options));assert.throws(()=>s.options.push('e'))})
test('invalid identifiers, score, phase and options fail closed',()=>{for(const patch of[{sessionId:'bad'},{score:751},{phase:'DEMO'},{revision:-1},{options:['a']},{eliminated:[1,1]},{reveal:{roundId:rid}},{phase:'REVEALING'},{serverNow:NaN}])assert.throws(()=>validateSnapshot({...snapshot(),...patch}),/INVALID_SESSION_SNAPSHOT/)})
test('reveal must belong to current round and cannot precede server decision',()=>{const reveal={roundId:rid,correct:0,selected:1,awarded:0,explanation:'Because'};assert.throws(()=>validateSnapshot({...snapshot(),reveal}));assert.equal(validateSnapshot({...snapshot(),phase:'REVEALING',reveal}).reveal.correct,0);assert.throws(()=>validateSnapshot({...snapshot(),phase:'REVEALING',reveal:{...reveal,roundId:sid}}))})
test('lower revisions and old server times never replace newer state',()=>{const current={...snapshot(),revision:5,serverNow:200};assert.equal(isNewer(current,{...current,revision:4,serverNow:300}),false);assert.equal(isNewer(current,{...current,serverNow:199}),false);assert.equal(isNewer(current,{...current,revision:6}),true);assert.equal(isNewer(current,{...current,sessionId:rid}),false)})
test('uncertain command clears only after matching authoritative outcome',()=>{const c={kind:'answer',sessionId:sid,roundId:rid};assert.equal(commandResolved(c,snapshot()),false);assert.equal(commandResolved(c,{...snapshot(),phase:'REVEALING'}),true);assert.equal(commandResolved(c,{...snapshot(),sessionId:rid,phase:'REVEALING'}),false);assert.equal(commandResolved({...c,kind:'fifty'},{...snapshot(),lifelineUsed:true}),true)})
import {validateVoiceCandidate} from '../src/server-state.js'
test('voice DTO stays explicitly unconfirmed and cannot leak scoring data',()=>{const s={...snapshot(),phase:'ANSWERING',opensAt:100,deadline:20100};const c={sessionId:sid,roundId:rid,choice:1,transcript:'B',expiresAt:20100,serverNow:500,requiresConfirmation:true};assert.equal(validateVoiceCandidate(c,s,600).choice,1);assert.ok(Object.isFrozen(validateVoiceCandidate(c,s,600)));for(const patch of[{requiresConfirmation:false},{roundId:sid},{expiresAt:20101},{choice:4},{correct:1},{transcript:'x'.repeat(161)}])assert.throws(()=>validateVoiceCandidate({...c,...patch},s,600));assert.throws(()=>validateVoiceCandidate(c,s,20100));assert.throws(()=>validateVoiceCandidate(c,{...s,phase:'REVEALING'},600));assert.throws(()=>validateVoiceCandidate(c,{...s,eliminated:[1]},600))})
