import {test,expect,vi,beforeEach,afterEach} from 'vitest'
import {createVoiceRecorder} from '../src/voice-recorder.js'
let tracks,context,node,media
beforeEach(()=>{vi.useFakeTimers();tracks=[{stop:vi.fn()}];media=vi.fn().mockResolvedValue({getTracks:()=>tracks});vi.stubGlobal('isSecureContext',true);vi.stubGlobal('navigator',{mediaDevices:{getUserMedia:media}});vi.stubGlobal('AudioContext',class{constructor(){this.sampleRate=48000;this.destination={};this.audioWorklet={addModule:vi.fn().mockResolvedValue()};this.close=vi.fn().mockResolvedValue();this.resume=vi.fn().mockResolvedValue();context=this}createMediaStreamSource(){return{connect:vi.fn(),disconnect:vi.fn()}}createGain(){return{gain:{value:1},connect:vi.fn(),disconnect:vi.fn()}}});vi.stubGlobal('AudioWorkletNode',class{constructor(){this.port={onmessage:null,close:vi.fn()};this.connect=vi.fn();this.disconnect=vi.fn();node=this}})})
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals()})
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve()}
test('constructing capture never requests microphone permission',()=>{createVoiceRecorder();expect(media).not.toHaveBeenCalled()})
test('explicit capture converts data and always stops tracks',async()=>{const capture=createVoiceRecorder();await capture.start();expect(media).toHaveBeenCalledWith({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});node.port.onmessage({data:{type:'samples',buffer:new Float32Array(4800).buffer}});const wave=capture.stop();expect(wave.length).toBe(3244);expect(tracks[0].stop).toHaveBeenCalled();expect(context.close).toHaveBeenCalled();expect(node.port.onmessage).toBeNull()})
test('permission resolved after cancellation stops tracks without connecting',async()=>{let allow;media.mockReturnValue(new Promise(r=>allow=r));const capture=createVoiceRecorder();const starting=capture.start();const rejection=expect(starting).rejects.toThrow('CAPTURE_CANCELLED');await flush();capture.cancel();allow({getTracks:()=>tracks});await rejection;expect(tracks[0].stop).toHaveBeenCalled();expect(context.close).toHaveBeenCalled()})
test('permission denial closes resources and never creates a worklet node',async()=>{media.mockRejectedValue({name:'NotAllowedError'});const capture=createVoiceRecorder();await expect(capture.start()).rejects.toThrow('MIC_PERMISSION_DENIED');expect(context.close).toHaveBeenCalled()})
test('permission prompt timeout is finite and a later grant is discarded',async()=>{let allow;media.mockReturnValue(new Promise(r=>allow=r));const capture=createVoiceRecorder();const p=capture.start();const rejected=expect(p).rejects.toThrow('MIC_SETUP_TIMEOUT');await flush();await vi.advanceTimersByTimeAsync(15000);await rejected;allow({getTracks:()=>tracks});await flush();expect(tracks[0].stop).toHaveBeenCalled();expect(context.close).toHaveBeenCalled()})
test('capture duration callback is bounded and cancellation clears it',async()=>{const limit=vi.fn(),capture=createVoiceRecorder({onLimit:limit,maxMillis:2000});await capture.start();vi.advanceTimersByTime(1999);expect(limit).not.toHaveBeenCalled();vi.advanceTimersByTime(1);expect(limit).toHaveBeenCalledTimes(1);capture.cancel();vi.advanceTimersByTime(10000);expect(limit).toHaveBeenCalledTimes(1)})
test('oversized worklet message closes input and reports an error',async()=>{const error=vi.fn(),capture=createVoiceRecorder({onError:error});await capture.start();node.port.onmessage({data:{type:'samples',buffer:new Float32Array(288001).buffer}});expect(error).toHaveBeenCalled();expect(tracks[0].stop).toHaveBeenCalled()})
test('cancel rejects a pending permission wait without waiting for native permission',async()=>{media.mockReturnValue(new Promise(()=>{}));const capture=createVoiceRecorder(),pending=capture.start();await flush();const rejected=expect(pending).rejects.toThrow('CAPTURE_CANCELLED');capture.cancel();await rejected;expect(context.close).toHaveBeenCalled()})
test('failed worklet load stops an already granted microphone',async()=>{const capture=createVoiceRecorder(),pending=capture.start();context.audioWorklet.addModule.mockRejectedValue(new Error('module unavailable'));await expect(pending).rejects.toThrow('MIC_UNAVAILABLE');expect(tracks[0].stop).toHaveBeenCalled();expect(context.close).toHaveBeenCalled()})
