<script setup>
import {computed,onMounted,onUnmounted,ref,nextTick} from 'vue'
import {gsap} from 'gsap'
import {questions} from './questions'
import {createGame,tick,answer,next,fifty,ANSWER_MS} from './engine'
import {createStudioAudio} from './audio'
import './style.css'
const language=ref(0),game=ref(null),now=ref(Date.now()),muted=ref(true),reduced=ref(false),narration=ref(false),candidate=ref(''),showVoice=ref(false),canvas=ref(null),stage=ref(null),notice=ref('')
const audio=createStudioAudio();let interval,raf,resizeObserver,motionQuery,speechFallback,speechVersion=0
const t=(zh,en)=>language.value?en:zh
const q=computed(()=>game.value?.deck[game.value.index]);const revealing=computed(()=>game.value?.phase==='revealing');const last=computed(()=>game.value?.results.at(-1));const finished=computed(()=>game.value?.phase==='finished')
const remaining=computed(()=>!game.value?20:Math.max(0,Math.ceil((game.value.deadline-now.value)/1000)))
const fraction=computed(()=>!game.value?1:game.value.phase==='reading'?1:Math.max(0,(game.value.deadline-now.value)/ANSWER_MS))
const canAnswer=computed(()=>game.value?.phase==='answering');const correctCount=computed(()=>game.value?.results.filter(r=>r.correct).length||0)
function animateStage(){if(reduced.value)return;nextTick(()=>gsap.fromTo(stage.value,{opacity:.3,y:18},{opacity:1,y:0,duration:.55,ease:'power3.out'}))}
function speak(){
 const version=++speechVersion;clearTimeout(speechFallback);window.speechSynthesis?.cancel()
 if(!game.value||!q.value)return
 const current=game.value,round=current.index
 const resume=()=>{if(game.value===current&&current.index===round&&current.phase==='reading'){current.opensAt=Date.now()+500;current.deadline=current.opensAt+ANSWER_MS}}
 if(!narration.value){resume();return}
 if(!('speechSynthesis'in window)){notice.value=t('浏览器朗读不可用，请按文字答题','Narration unavailable. Read the question on screen.');resume();return}
 const holding=current.phase==='reading'
 if(holding){current.opensAt=Date.now()+30000;current.deadline=current.opensAt+ANSWER_MS}
 const u=new SpeechSynthesisUtterance(q.value.title[language.value]+'. '+q.value.options[language.value].map((v,i)=>`${'ABCD'[i]}, ${v}`).join('. '))
 u.lang=language.value?'en-US':'zh-CN';u.rate=1
 const done=()=>{if(version!==speechVersion)return;clearTimeout(speechFallback);if(holding)resume()}
 u.onend=done;u.onerror=done
 speechFallback=setTimeout(()=>{window.speechSynthesis.cancel();done()},25000)
 window.speechSynthesis.speak(u)
}
function start(){game.value=createGame(questions,Date.now());now.value=Date.now();showVoice.value=false;candidate.value='';notice.value='';animateStage();if(narration.value)speak()}
function choose(i){if(!canAnswer.value)return;if(answer(game.value,i,Date.now())){audio.cue(last.value.correct?'correct':'wrong');speechVersion++;clearTimeout(speechFallback);window.speechSynthesis?.cancel();candidate.value='';showVoice.value=false;animateStage()}}
function leave(){speechVersion++;clearTimeout(speechFallback);game.value=null;window.speechSynthesis?.cancel();showVoice.value=false;candidate.value=''}
function advance(){if(!next(game.value,Date.now()))return;now.value=Date.now();showVoice.value=false;candidate.value='';animateStage();if(!finished.value&&narration.value)speak()}
function useFifty(){if(fifty(game.value,Date.now()))audio.cue('select')}
function confirmCandidate(){const index='ABCD'.indexOf(candidate.value.trim().toUpperCase());if(index>=0)choose(index)}
async function sound(){muted.value=!muted.value;if(muted.value){narration.value=false;speechVersion++;clearTimeout(speechFallback);window.speechSynthesis?.cancel();if(game.value?.phase==='reading'){game.value.opensAt=Date.now()+500;game.value.deadline=game.value.opensAt+ANSWER_MS}}try{await audio.enable(!muted.value)}catch{muted.value=true;notice.value=t('此浏览器暂不能启动音频，可继续答题','Audio unavailable. You can keep playing.')}}
function toggleLanguage(){if(game.value&&!finished.value){notice.value=t('语言在新一局生效，请先完成本局','Finish this game before changing language');return}language.value=1-language.value}
function keyboard(e){if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;const key=e.key.toUpperCase();const n='ABCD'.indexOf(key);if(n>=0)choose(n);else if(/^[1-4]$/.test(key))choose(Number(key)-1)}
function visibility(){audio.enable(!muted.value&&!document.hidden).catch(()=>{});if(document.hidden){speechVersion++;window.speechSynthesis?.cancel();clearTimeout(speechFallback);if(game.value?.phase==='reading'){game.value.opensAt=Date.now()+500;game.value.deadline=game.value.opensAt+ANSWER_MS}}if(game.value)tick(game.value,Date.now());motion()}
function paint(){cancelAnimationFrame(raf);const el=canvas.value;if(!el)return;const ctx=el.getContext('2d');const w=el.clientWidth,h=el.clientHeight,d=Math.min(window.devicePixelRatio||1,2);if(el.width!==w*d||el.height!==h*d){el.width=w*d;el.height=h*d}ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const time=reduced.value?0:performance.now()/18000;for(let i=0;i<55;i++){let x=((Math.sin(i*19.17)*.5+.5)*w),y=((i*71.13+time*10)%h);ctx.fillStyle=`rgba(184,210,255,${.1+(Math.sin(i+time)+1)*.12})`;ctx.beginPath();ctx.arc(x,y,i%5===0?1.4:.65,0,Math.PI*2);ctx.fill()}if(!reduced.value&&!document.hidden)raf=requestAnimationFrame(paint)}
function motion(){cancelAnimationFrame(raf);paint()}
onMounted(()=>{motionQuery=matchMedia('(prefers-reduced-motion: reduce)');reduced.value=motionQuery.matches;motionQuery.addEventListener('change',onMotion);interval=setInterval(()=>{now.value=Date.now();if(game.value)tick(game.value,now.value)},100);window.addEventListener('keydown',keyboard);document.addEventListener('visibilitychange',visibility);resizeObserver=new ResizeObserver(motion);resizeObserver.observe(canvas.value);paint()})
function onMotion(e){reduced.value=e.matches;motion()}
onUnmounted(()=>{clearTimeout(speechFallback);clearInterval(interval);cancelAnimationFrame(raf);resizeObserver?.disconnect();motionQuery?.removeEventListener('change',onMotion);window.removeEventListener('keydown',keyboard);document.removeEventListener('visibilitychange',visibility);window.speechSynthesis?.cancel();audio.close();gsap.killTweensOf(stage.value)})
</script>

<template>
<div class="studio" :class="{'quiet-motion':reduced,'in-play':game&&!finished}">
 <canvas ref="canvas" class="stars" aria-hidden="true"></canvas><div class="beam beam-left"></div><div class="beam beam-right"></div><div class="floor"></div><div class="horizon"></div>
 <header class="topbar"><a class="brand" href="#" @click.prevent="!game||finished?game=null:notice=t('本局进行中','Game in progress')"><span class="brand-mark">Q<span>✦</span></span><span>环球挑战<small>QUIZ CHALLENGE</small></span></a><div class="studio-label"><span></span>{{t('原创竞猜演播厅','THE QUIZ STUDIO')}}<em>01</em></div><nav aria-label="Settings"><button @click="sound" :aria-pressed="!muted" :title="t('音效与音乐','Music and sound')">{{muted?'♫ ×':'♫'}}<span class="nav-label">{{t(muted?'声音关':'声音开',muted?'SOUND OFF':'SOUND ON')}}</span></button><button @click="toggleLanguage">{{language?'EN':'中文'}}</button><button @click="reduced=!reduced;motion()" :aria-pressed="reduced" :title="t('减少动画','Reduce motion')">{{reduced?'◌':'✧'}}<span class="sr-only">{{t('减少动画','Reduce motion')}}</span></button></nav></header>
 <div class="demo-ribbon">{{t('本地演示 · 不上传成绩 · 非正式题库','LOCAL DEMO · NO SCORES UPLOADED · SAMPLE QUESTIONS')}}</div>
 <p v-if="notice" class="notice" role="status">{{notice}}<button @click="notice=''" aria-label="Dismiss">×</button></p>
 <main ref="stage" class="main-stage">
  <section v-if="!game" class="lobby">
   <div class="hero-copy"><div class="eyebrow"><i></i>{{t('一场属于你的知识高光','YOUR MOMENT IN THE SPOTLIGHT')}}</div><h1>{{t('世界很大，','A world of wonder.')}}<br><span>{{t('轮到你发光。','Your time to shine.')}}</span></h1><p class="intro">{{t('五道挑战，四个选项。跟随聚光灯，','Five questions. Four choices. Follow the spotlight,')}}<br>{{t('让每一次正确，点亮下一段旅程。','and let every answer take you further.')}}</p><div class="feature-line"><span>05 <small>{{t('道闯关','ROUNDS')}}</small></span><b></b><span>20<small>{{t('秒决胜','SECONDS')}}</small></span><b></b><span>750<small>{{t('满分挑战','MAX POINTS')}}</small></span></div><button class="start-button" @click="start"><span>▶</span>{{t('登上舞台','TAKE THE STAGE')}}<i>↗</i></button><div class="below-start"><span class="kbd">1–4</span>{{t('或 A–D 键盘作答','or A–D to answer')}}<span>·</span>{{t('无需登录体验','No sign-in needed for demo')}}</div></div>
   <div class="hero-art" aria-hidden="true"><div class="orbital orbit-one"></div><div class="orbital orbit-two"></div><div class="orbit-dot dot-one"></div><div class="orbit-dot dot-two"></div><svg class="globe" viewBox="0 0 400 400"><defs><radialGradient id="glow"><stop stop-color="#5270ba" stop-opacity=".28"/><stop offset="1" stop-color="#0c173a" stop-opacity=".4"/></radialGradient><linearGradient id="gold"><stop stop-color="#ffe4a6"/><stop offset="1" stop-color="#ab7943"/></linearGradient></defs><circle cx="200" cy="200" r="154" fill="url(#glow)" stroke="#6685c6" stroke-opacity=".5"/><g fill="none" stroke="#7d9cdf" stroke-opacity=".23"><ellipse cx="200" cy="200" rx="70" ry="154"/><ellipse cx="200" cy="200" rx="125" ry="154"/><ellipse cx="200" cy="200" rx="154" ry="58"/><ellipse cx="200" cy="200" rx="154" ry="110"/><path d="M46 200h308M200 46v308"/></g><path d="M110 140l36-30 43 10 14 25-26 33-7 39-26-12-11-33-32-9zm98 33 24-34 40 13 26 34-15 20-25-5-2 41-23 36-20-14-12-52z" fill="#789adc" fill-opacity=".25" stroke="#9ab5ef" stroke-opacity=".45"/><path d="M97 286Q200 365 306 284" fill="none" stroke="url(#gold)" stroke-width="2"/></svg><div class="hero-number">Q<span>✦</span></div><div class="art-tag tag-science"><span>✦</span>{{t('宇宙探索','SPACE')}}</div><div class="art-tag tag-culture"><span>◈</span>{{t('世界人文','CULTURE')}}</div><div class="art-tag tag-nature"><span>⌁</span>{{t('自然万象','NATURE')}}</div><div class="platform"><span></span></div><p class="art-caption">THE WORLD IS YOUR STAGE</p></div>
   <div class="lobby-bottom"><span class="line"></span><span>DISCOVER · THINK · SHINE</span><span class="line"></span></div>
  </section>
  <section v-else-if="finished" class="finale"><div class="eyebrow">{{t('今晚的聚光灯，属于你','THE SPOTLIGHT IS YOURS')}}</div><div class="award">✦</div><h1>{{t(game.score===750?'完美通关！':'精彩落幕！',game.score===750?'A perfect run!':'What a performance!')}}</h1><div class="final-score">{{game.score}}<small>/ 750</small></div><p>{{t(`答对 ${correctCount} / 5 题 · 最佳连胜 ${game.bestStreak}`,`${correctCount} / 5 correct · Best streak ${game.bestStreak}`)}}</p><div class="review-strip"><span v-for="(r,i) in game.results" :key="r.id" :class="{correct:r.correct}"><small>0{{i+1}}</small>{{r.correct?'✓':'−'}}<b>+{{r.points}}</b></span></div><button class="start-button" @click="start">{{t('再来一局','PLAY AGAIN')}}<i>↗</i></button><button class="text-button" @click="game=null">{{t('返回演播厅','Back to the studio')}}</button><p class="fine-print">{{t('演示成绩仅保留于本次页面，不同步到账号','Demo results stay in this page and are not saved to an account')}}</p></section>
  <section v-else class="play-layout">
   <div class="game-bar"><button class="text-button" @click="leave">← {{t('离开本局','Leave game')}}</button><div class="round-dots"><span v-for="n in 5" :class="{current:n===game.index+1,done:n<=game.index}">{{n<=game.index?'✓':String(n).padStart(2,'0')}}</span></div><div class="score-label">{{t('当前积分','SCORE')}} <strong>{{game.score}}</strong></div></div>
   <div class="question-stage"><div class="question-meta"><span class="category">{{q.category[language]}}</span><span>{{t('第','ROUND')}} {{String(game.index+1).padStart(2,'0')}} <i>/ 05</i></span></div><div class="question-row"><h2>{{q.title[language]}}</h2><div class="countdown" :class="{urgent:remaining<=5&&canAnswer,locked:!canAnswer}"><svg viewBox="0 0 100 100"><circle class="track" cx="50" cy="50" r="44"/><circle class="progress" cx="50" cy="50" r="44" :style="{strokeDashoffset:276.46*(1-fraction)}"/></svg><span>{{revealing?(last.correct?'✓':'−'):game.phase==='reading'?'···':remaining}}<small>{{revealing?t('已揭晓','RESULT'):game.phase==='reading'?t('读题中','READ'):t('秒','SEC')}}</small></span></div></div><div class="stage-divider"><span></span><i>✦</i><span></span></div><p class="phase-message" role="status">{{game.phase==='reading'?t('准备好，聚光灯即将亮起…','Get ready. The spotlight is coming…'):revealing?(last.correct?t('漂亮！正确答案已点亮','Brilliant! You found the right answer'):last.choice===null?t('时间到，下一题再战','Time is up. On to the next challenge'):t('差一点！把新知识收入囊中','So close! A new fact for your journey')):t('相信你的判断，锁定一个答案','Trust your instinct. Lock in your answer')}}</p></div>
   <div class="answers"><button v-for="(option,i) in q.options[language]" :key="q.id+'-'+i" :disabled="!canAnswer||game.eliminated.includes(i)" @click="choose(i)" :class="{eliminated:game.eliminated.includes(i),right:revealing&&i===q.answer,wrong:revealing&&last.choice===i&&!last.correct,selected:revealing&&last.choice===i}"><span class="answer-key">{{'ABCD'[i]}}</span><span>{{game.eliminated.includes(i)?'—':option}}</span><b class="answer-status">{{revealing&&i===q.answer?'✓':revealing&&last.choice===i?'×':'↗'}}</b></button></div>
   <div v-if="revealing" class="reveal" aria-live="polite"><div><span>{{last.correct?`+${last.points} ${t('分','PTS')}`:t('知识入袋','GOOD TO KNOW')}}</span><p>{{q.explain[language]}}</p></div><button class="next-button" @click="advance">{{game.index===4?t('查看成绩','SEE RESULTS'):t('下一道挑战','NEXT QUESTION')}} →</button></div>
   <div v-else class="lifelines"><button @click="useFifty" :disabled="!canAnswer||game.lifelineUsed"><strong>50:50</strong>{{t(game.lifelineUsed?'已使用':'去掉两个错误答案',game.lifelineUsed?'USED':'REMOVE TWO')}}</button><button @click="showVoice=!showVoice" :disabled="!canAnswer"><strong>⌁</strong>{{t('语音确认体验','VOICE CONFIRM DEMO')}}</button><label title="浏览器语音服务可能由设备或浏览器提供商处理题目文本"><input type="checkbox" v-model="narration" @change="speak">{{t('浏览器朗读体验','Browser narration demo')}}</label><span class="streak">{{game.streak?'✦ '+game.streak+' '+t('连胜','STREAK'):t('每一次判断，都有力量','EVERY ANSWER COUNTS')}}</span></div>
   <div v-if="showVoice&&canAnswer" class="voice-demo"><p>{{t('当前未接麦克风识别。输入模拟识别候选，确认后才提交；倒计时继续。','Microphone recognition is not connected. Enter a simulated candidate and confirm to submit. The clock keeps running.')}}</p><select v-model="candidate" aria-label="模拟识别候选"><option value="">{{t('选择 A–D','Choose A–D')}}</option><option v-for="(a,i) in 'ABCD'" :disabled="game.eliminated.includes(i)">{{a}}</option></select><button @click="confirmCandidate" :disabled="!candidate">{{t('确认答案','CONFIRM ANSWER')}}</button></div>
  </section>
 </main><footer><span>QUIZ CHALLENGE <i>✦</i> {{t('让好奇心，成为你的超能力','CURIOSITY IS YOUR SUPERPOWER')}}</span><span>ORIGINAL STUDIO EXPERIENCE</span></footer>
</div>
</template>
