<script setup>
import {ref,watch,onBeforeUnmount,onMounted} from 'vue'
import {createQuizApi} from './server-api.js'
const props=defineProps({api:{type:Object,default:()=>createQuizApi()}})
const version=ref(''),locale=ref('zh-CN'),document=ref(''),filename=ref(''),reason=ref(''),preview=ref(null),confirmed=ref(false),busy=ref(false),error=ref(''),published=ref(null)
let epoch=0,controller=null,fileEpoch=0
const errors={CONTENT_PUBLICATION_NOT_CONFIGURED:'尚未接入题包维护权限或发布服务',IDENTITY_ADAPTER_NOT_CONFIGURED:'尚未接入原系统身份',CONTENT_PUBLICATION_FORBIDDEN:'当前账户没有全局题包发布权限',AUTHENTICATION_REQUIRED:'登录已失效，请回到原系统登录',PACK_VERSION_CONFLICT:'这个版本已存在且内容或审核记录不同，请使用新版本',PACK_PREVIEW_CHANGED:'预览已失效，请重新校验',QUESTION_PACK_INVALID:'题包格式、题目审核信息或关卡覆盖未通过校验',INVALID_PACK_IDENTITY:'请检查版本号与语言',PUBLICATION_REASON_REQUIRED:'请填写审核依据',RATE_LIMITED:'请求过于频繁，请稍后重试'}
function invalidate(){epoch++;controller?.abort();controller=null;busy.value=false;preview.value=null;confirmed.value=false;published.value=null;error.value=''}
watch([version,locale,document,reason],invalidate,{flush:'sync'})
async function loadFile(event){const id=++fileEpoch;invalidate();document.value='';filename.value='';const file=event.target.files?.[0];if(!file)return;if(file.size>262144){error.value='题包最多 256 KiB';return}try{const text=await file.text();if(id!==fileEpoch)return;document.value=text;filename.value=file.name}catch{if(id===fileEpoch)error.value='无法读取文件'}}
function input(){return {version:version.value,locale:locale.value,document:document.value,reason:reason.value,previewHash:preview.value?.previewHash??null}}
async function act(publish){if(busy.value||!document.value||!version.value)return;if(publish&&(!confirmed.value||!preview.value||!reason.value.trim()))return;const id=++epoch;controller=new AbortController();busy.value=true;error.value='';try{const result=await (publish?props.api.publishPack(input(),controller.signal):props.api.previewPack(input(),controller.signal));if(id!==epoch)return;if(publish){if(result?.version!==version.value||result?.locale!==locale.value||result?.contentSha256!==preview.value?.contentSha256||typeof result?.created!=='boolean')throw new Error('Invalid publication receipt');published.value=result;confirmed.value=false}else{if(result?.version!==version.value||result?.locale!==locale.value||!/^([a-f0-9]{64})$/.test(result?.previewHash)||!/^([a-f0-9]{64})$/.test(result?.contentSha256)||![2,3,4].includes(result?.schemaVersion)||!['AVAILABLE','IDENTICAL'].includes(result?.versionState)||![result?.questionCount,result?.routeCount,result?.chapterCount].every(Number.isSafeInteger))throw new Error('Invalid preview');preview.value=result;confirmed.value=false}}catch(e){if(id===epoch){error.value=errors[e.code]||'请求未完成，可重新校验；发布重试不会重复写入相同版本';confirmed.value=false;preview.value=null}}finally{if(id===epoch){busy.value=false;controller=null}}}
function hidden(){if(globalThis.document.hidden)invalidate()}
function hide(){fileEpoch++;invalidate();document.value='';filename.value=''}
onMounted(()=>{globalThis.document.addEventListener('visibilitychange',hidden);window.addEventListener('pagehide',hide)})
onBeforeUnmount(()=>{fileEpoch++;invalidate();globalThis.document.removeEventListener('visibilitychange',hidden);window.removeEventListener('pagehide',hide)})
</script>
<template>
<main class="publisher"><a href="./server.html">← 返回挑战舞台</a><p class="eyebrow">环球挑战 · 内容工作台</p><h1>让下一场挑战准备就绪</h1><p class="intro">上传已审校的文本题包，核对服务器预览后发布。题包供所有站点使用，需要原系统明确授予的全局内容权限。</p>
<form @submit.prevent="act(false)"><div class="fields"><label>不可变版本号<input v-model="version" maxlength="80" pattern="[A-Za-z0-9][A-Za-z0-9._-]{0,79}" required placeholder="world-foundations-r4"></label><label>语言<select v-model="locale"><option value="zh-CN">简体中文</option><option value="en">English</option></select></label></div><label class="upload">选择题包 JSON<input type="file" accept=".json,application/json" @change="loadFile"><span>{{ filename||'支持服务器文本题包 schema 2 / 3 / 4，最大 256 KiB' }}</span></label><label>审核依据<textarea v-model="reason" maxlength="1000" rows="3" placeholder="说明事实、翻译和使用权核查依据；如为助手审校请明确标注"></textarea></label><button :disabled="busy||!document||!version" type="submit">{{busy?'正在核验…':'校验并预览'}}</button></form>
<p v-if="error" role="alert" class="error">{{error}}</p>
<section v-if="preview" class="preview" aria-label="发布预览"><h2>服务器已校验</h2><p>{{preview.version}} · {{preview.locale}} · schema {{preview.schemaVersion}}</p><dl><div><dt>题目</dt><dd>{{preview.questionCount}}</dd></div><div><dt>路线</dt><dd>{{preview.routeCount}}</dd></div><div><dt>章节</dt><dd>{{preview.chapterCount}}</dd></div></dl><p>{{preview.versionState==='IDENTICAL'?'同一版本与内容已存在，重试不会重复发布':'这是一个新版本'}}</p><p class="digest">SHA-256 {{preview.contentSha256}}</p><label class="confirm"><input v-model="confirmed" type="checkbox">我已核对版本、语言、文本审校与使用权依据，确认立即作为全局题包发布</label><button type="button" :disabled="busy||!confirmed||!reason.trim()" @click="act(true)">确认发布文本题包</button></section>
<p v-if="published" role="status" class="success">{{published.created?'题包与审核记录已一并保存':'同一题包已保存，无重复写入'}}。玩家下一次开局可使用当前有效题包，已开始的挑战继续使用原题目。</p><p class="note">自动校验检查结构、来源链接与审核字段，不替代事实审校。此操作不批准音频，也不会上传模型权重。发布失败不会生成半份题包。</p>
</main>
</template>
<style scoped>
:global(body){margin:0;background:#080d21;color:#edf3ff;font-family:system-ui,sans-serif}.publisher{max-width:800px;margin:auto;padding:42px 24px 80px}.publisher a{color:#a9c7ff}.eyebrow{letter-spacing:.18em;color:#a4b8df;margin-top:42px}h1{font-size:clamp(28px,5vw,42px);line-height:1.2}.intro,.note{color:#adbdd9;line-height:1.7}form,.preview{background:#121c36;border:1px solid #344766;border-radius:20px;padding:24px;margin:24px 0}.fields{display:grid;grid-template-columns:2fr 1fr;gap:18px}label{display:grid;gap:9px;margin-bottom:20px}input,select,textarea,button{font:inherit;border-radius:10px;padding:12px;color:inherit}input,select,textarea{box-sizing:border-box;width:100%;background:#090f23;border:1px solid #587092}button{background:#e4ba60;color:#151020;border:0;min-height:48px;font-weight:700;cursor:pointer}button:disabled{opacity:.5;cursor:default}.upload{border:1px dashed #769bd0;padding:18px;border-radius:12px}.upload span,.digest{font-size:13px;color:#adbdd9;overflow-wrap:anywhere}dl{display:flex;gap:48px}dd{margin:6px 0;font-size:30px}dt{color:#adbdd9}.confirm{display:flex;align-items:flex-start;line-height:1.6}.confirm input{width:22px;height:22px;flex:none}.error{color:#ffb3bc}.success{color:#9ee4c4;line-height:1.7}:focus-visible{outline:3px solid #94bfff;outline-offset:4px}@media(max-width:560px){.fields{grid-template-columns:1fr}.publisher{padding:24px 16px}form,.preview{padding:18px}button{width:100%}}
</style>
