<script setup>
import {onMounted,onUnmounted,ref,shallowRef,watch} from 'vue'
import {validateJourney} from './journey'
import {categoryName} from './challenges'
const props=defineProps({api:Object,locale:String,disabled:Boolean});const emit=defineEmits(['play','expired'])
const journey=shallowRef(null),busy=ref(false),error=ref('');let generation=0,controller,alive=true
const t=(zh,en)=>props.locale==='en'?en:zh
function cancel(){generation++;controller?.abort();journey.value=null;busy.value=false;error.value=''}
async function load(){if(!alive||props.disabled||document.hidden)return;cancel();const token=generation,locale=props.locale;controller=new AbortController();busy.value=true;try{const result=validateJourney(await props.api.journey(locale,controller.signal),locale);if(alive&&token===generation)journey.value=result}catch(e){if(!alive||token!==generation)return;if([401,403].includes(e.status)){cancel();emit('expired',e)}else error.value=t('章节地图暂不可用，请重试。不会假定任何关卡已解锁','The chapter map is unavailable. Retry; no unlock is assumed.')}finally{if(token===generation)busy.value=false}}
function play(level){if(!props.disabled&&!busy.value&&level.unlocked&&journey.value)emit('play',{chapterId:level.id,version:journey.value.version})}
function visibility(){if(document.hidden)cancel();else load()}
watch(()=>props.locale,()=>{cancel();load()});watch(()=>props.disabled,value=>{if(value){generation++;controller?.abort();busy.value=false}})
onMounted(()=>{document.addEventListener('visibilitychange',visibility);load()})
onUnmounted(()=>{alive=false;cancel();document.removeEventListener('visibilitychange',visibility)})
</script>
<template><section class="journey-map" :aria-label="t('章节旅程','Chapter journey')">
<div class="journey-heading"><div><span class="eyebrow">THREE CHAPTERS · ONE JOURNEY</span><h2>{{journey?.title||t('点亮你的知识旅程','Light up your knowledge journey')}}</h2><p>{{t('达标通关，解锁下一章。已解锁章节可随时重玩','Meet the target to unlock the next chapter. Replay any unlocked chapter.')}}</p></div><button class="text-button" @click="load" :disabled="busy||disabled">{{busy?t('读取进度…','LOADING…'):t('刷新进度','REFRESH')}}</button></div>
<p v-if="error" role="alert" class="challenge-note">{{error}}</p><p v-if="busy" role="status" class="challenge-note">{{t('正在读取服务器保存的进度','Reading your saved server progress')}}</p><p v-if="journey&&!journey.levels.length" class="challenge-note">{{t('当前审核题包尚未提供章节旅程，可选择自由挑战','This approved pack has no chapter journey yet. Free challenges remain available.')}}</p>
<ol v-if="journey?.levels.length" class="journey-path"><li v-for="level in journey.levels" :key="level.id" :class="{locked:!level.unlocked,cleared:level.passed}"><div class="journey-node" aria-hidden="true">{{level.passed?'✦':String(level.index).padStart(2,'0')}}</div><div class="journey-chapter"><div class="journey-status">{{level.passed?t('已通关','CLEARED'):level.unlocked?t('已解锁','UNLOCKED'):t('尚未解锁','LOCKED')}}</div><h3>{{level.title}}</h3><p>{{t(`五题答对至少 ${level.requiredCorrect} 题通关`,`Answer at least ${level.requiredCorrect} of five correctly to clear`)}}</p><div class="challenge-steps"><span v-for="(slot,i) in level.slots" :key="i">{{categoryName(slot.category,locale==='en')}} <i>{{'●'.repeat(slot.difficulty)}}</i></span></div><p class="journey-record">{{t(`已完成 ${level.attempts} 次 · 最佳 ${level.bestScore} 分 · 答对 ${level.bestCorrect}/5`,`Completed ${level.attempts} · Best ${level.bestScore} points · ${level.bestCorrect}/5 correct`)}}</p><button class="next-button" @click="play(level)" :disabled="!level.unlocked||disabled||busy">{{!level.unlocked?t('先通关上一章','CLEAR THE PREVIOUS CHAPTER'):level.attempts?t('重玩本章','REPLAY CHAPTER'):t('进入本章','ENTER CHAPTER')}} <span v-if="level.unlocked">→</span></button></div></li></ol>
<p class="fine-print">{{t('难度为编辑估计；进度由服务器按当前旅程规则版本保存','Difficulty is editorial. Progress is saved by the server for this journey rules version.')}}</p>
</section></template>
<style>
.journey-map{margin:30px 0 40px}.journey-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.journey-heading h2{font-size:26px;font-weight:500;color:#e8d7b2;margin:12px 0}.journey-heading p{font-size:11px;line-height:1.8;color:#92a4c3}.journey-path{list-style:none;padding:10px 0 0;margin:0}.journey-path li{position:relative;display:flex;gap:24px;padding-bottom:28px}.journey-path li:not(:last-child):before{content:'';position:absolute;left:25px;top:50px;bottom:0;width:1px;background:linear-gradient(#caad7044,#7185b155)}.journey-node{flex:0 0 52px;height:52px;display:grid;place-items:center;border:1px solid #bea66c99;border-radius:50%;color:#dec390;font:20px Georgia;background:radial-gradient(#ba9c472c,#10203b);box-shadow:0 0 30px #c7a45912}.journey-chapter{flex:1;padding:2px 0 22px;border-bottom:1px solid #6e82a422}.journey-status{font-size:8px;letter-spacing:.2em;color:#b69c68}.journey-chapter h3{font-size:21px;font-weight:500;margin:10px 0;color:#dce4f2}.journey-chapter p{font-size:10px;line-height:1.8;color:#9aaaca}.journey-chapter .journey-record{font-size:9px;color:#b29f7b;margin:16px 0}.journey-path .locked .journey-node{border-color:#6d7a9144;color:#6e7b97;box-shadow:none}.journey-path .locked .journey-chapter{opacity:.58}.journey-path .cleared .journey-node{background:radial-gradient(#c3a45a44,#15223b);color:#f6d389}.journey-path button:disabled{opacity:.45;cursor:not-allowed}@media(max-width:680px){.journey-heading h2{font-size:21px}.journey-heading{gap:12px}.journey-heading .eyebrow{font-size:7px}.journey-path li{gap:16px}.journey-chapter h3{font-size:18px}.journey-chapter .next-button{font-size:9px;padding:12px}.journey-heading p{font-size:10px}}
</style>
