// Original demo wording; not an approved production question pack. Answers stay local in demo only.
export const questions = [
 {id:'earth-ocean',category:['蓝色星球','OUR PLANET'],title:['地球上面积最大的海洋，是哪一个？','Which is the largest ocean on Earth?'],options:[['太平洋','大西洋','印度洋','北冰洋'],['Pacific','Atlantic','Indian','Arctic']],answer:0,explain:['太平洋是地球上面积最大的海洋。','The Pacific is the largest ocean on Earth.']},
 {id:'mars',category:['宇宙探索','SPACE'],title:['哪颗行星常被称为「红色星球」？','Which planet is often called the Red Planet?'],options:[['金星','火星','木星','海王星'],['Venus','Mars','Jupiter','Neptune']],answer:1,explain:['火星表面的含铁矿物氧化，让它呈现红色。','Oxidized iron minerals give Mars its reddish appearance.']},
 {id:'octopus',category:['自然万象','NATURE'],title:['章鱼通常有几条腕？','How many arms does an octopus usually have?'],options:[['六条','十条','八条','十二条'],['Six','Ten','Eight','Twelve']],answer:2,explain:['章鱼有八条腕；鱿鱼则有八条腕和两条较长的触腕。','An octopus has eight arms. Squid have eight arms and two longer tentacles.']},
 {id:'water',category:['科学时刻','SCIENCE'],title:['水的化学式是什么？','What is the chemical formula for water?'],options:[['CO₂','O₂','NaCl','H₂O'],['CO₂','O₂','NaCl','H₂O']],answer:3,explain:['一个水分子由两个氢原子和一个氧原子组成。','A water molecule contains two hydrogen atoms and one oxygen atom.']},
 {id:'moon',category:['宇宙探索','SPACE'],title:['月球表面为什么会在夜空中发亮？','Why does the Moon appear bright in our night sky?'],options:[['反射太阳光','自身燃烧发光','反射地球城市灯光','由闪电照亮'],['It reflects sunlight','It burns like a star','It reflects city lights','It is lit by lightning']],answer:0,explain:['我们看到的月光主要是月球表面反射的太阳光。','Moonlight is primarily sunlight reflected from the lunar surface.']},
 {id:'compass',category:['环球旅行','EXPLORATION'],title:['罗盘上的字母 E 代表哪个方向？','Which direction does E represent on a compass?'],options:[['北','东','南','西'],['North','East','South','West']],answer:1,explain:['E 是 East 的缩写，表示东方。','E stands for East.']},
 {id:'triangle',category:['逻辑空间','LOGIC'],title:['在平面欧几里得几何中，三角形内角和为多少？','In Euclidean geometry, what is the sum of a triangle’s interior angles?'],options:[['90°','270°','180°','360°'],['90°','270°','180°','360°']],answer:2,explain:['平面欧几里得几何中的三角形内角和是180°。','The interior angles of a Euclidean triangle sum to 180°.']},
 {id:'piano',category:['艺术灵感','ARTS'],title:['标准现代钢琴通常有多少个琴键？','How many keys does a standard modern piano usually have?'],options:[['61个','76个','88个','96个'],['61','76','88','96']],answer:2,explain:['标准现代钢琴通常有88键：52个白键和36个黑键。','A standard modern piano usually has 88 keys: 52 white and 36 black.']}
]
