<script setup>
import {computed,onMounted,onUnmounted,ref,shallowRef} from 'vue'
import {createQuizApi,QuizApiError} from './server-api'
import {validateSnapshot,isNewer,commandResolved} from './server-state'
import {createStudioAudio} from './audio'
import './style.css'
const api=createQuizApi(),audio=createStudioAudio(),KEY='quiz.server.session.v1'
const session=shallowRef(null),pending=shallowRef(null),fault=shallowRef(null),busy=ref(false),syncing=ref(false),locale=ref('zh-CN'),muted=ref(true),reduced=ref(false),wall=ref(Date.now()),offset=ref(0)
let epoch=0,alive=true,timer,lastPoll=0,lastSoundRound=null,resumeId=null
const en=computed(()=>locale.value==='en'),t=(zh,enText)=>en.value?enText:zh
const projectedNow=computed(()=>wall.value+offset.value)
const phase=computed(()=>{if(!session.value)return 'IDLE';if(session.value.phase==='READING'&&projectedNow.value>=session.value.opensAt)return projectedNow.value>=session.value.deadline?'SYNCING':'ANSWERING';if(session.value.phase==='ANSWERING'&&projectedNow.value>=session.value.deadline)return'SYNCING';return session.value.phase})
const remaining=computed(()=>session.value?Math.max(0,Math.ceil(((phase.value==='LOADING'?session.value.loadingDeadline:session.value.deadline)-projectedNow.value)/1000)):0)
const fraction=computed(()=>!session.value?1:phase.value==='LOADING'||phase.value==='READING'?1:Math.max(0,Math.min(1,(session.value.deadline-projectedNow.value)/(session.value.deadline-session.value.opensAt||20000))))
const canAnswer=computed(()=>session.value&&phase.value==='ANSWERING'&&!busy.value&&!pending.value)
const revealed=computed(()=>session.value?.phase==='REVEALING')
const message=computed(()=>{const code=fault.value?.code;return ({IDENTITY_ADAPTER_NOT_CONFIGURED:t('现有登录服务尚未接入，当前安全停止开局','Existing sign-in is not connected. Starting is safely blocked.'),DISTRIBUTED_ADMISSION_NOT_CONFIGURED:t('服务端限流尚未配置，当前安全停止开局','Distributed admission is not configured. Starting is safely blocked.'),QUESTION_BANK_UNAVAILABLE:t('还没有满足发布条件的正式题包','No approved question pack is available.'),AUTHENTICATION_REQUIRED:t('登录已失效，请通过原系统登录后重新连接','Your sign-in expired. Sign in through the existing system, then reconnect.'),SESSION_NOT_FOUND:t('该会话不属于当前登录范围或已不可用','This session is unavailable for the current identity.'),RATE_LIMITED:t('操作较频繁，请稍后重试','Too many requests. Please try again shortly.'),NETWORK_ERROR:t('网络中断。服务器仍在计时，可重试同一请求','Connection lost. The server clock continues. Retry the same request.'),REQUEST_TIMEOUT:t('请求未及时返回。请重试同一请求或同步结果','The request timed out. Retry the same request or sync the result.'),ANSWER_DEADLINE_PASSED:t('服务器判定已超时，正在同步结果','The server deadline passed. Syncing the result.'),READY_DEADLINE_PASSED:t('准备时间已过，本局已结束','The readiness window expired. This game is closed.')})[code]||t('服务暂不可用，未在本地生成结果','Service unavailable. No result has been generated locally.')})
function save(s){resumeId=s.sessionId;try{sessionStorage.setItem(KEY,JSON.stringify({sessionId:s.sessionId,locale:s.locale}))}catch{}}
function clearHint(){resumeId=null;try{sessionStorage.removeItem(KEY)}catch{}}
function accept(raw,expectedId,sent){const s=validateSnapshot(raw);if(expectedId&&s.sessionId!==expectedId)throw new QuizApiError('INVALID_SESSION_SNAPSHOT',502);if(!isNewer(session.value,s))return false;session.value=s;locale.value=s.locale;offset.value=s.serverNow-(sent+Date.now())/2;wall.value=Date.now();save(s);if(s.reveal&&lastSoundRound!==s.roundId){lastSoundRound=s.roundId;audio.cue(s.reveal.awarded>0?'correct':'wrong')}return true}
function safeFailure(e){return e instanceof QuizApiError?e:new QuizApiError('NETWORK_ERROR')}
async function run(command){if(busy.value||!alive)return;const token=epoch;busy.value=true;pending.value=command;fault.value=null;const sent=Date.now();try{const data=await command.call();if(!alive||token!==epoch)return;accept(data.session||data,command.sessionId,sent);pending.value=null}catch(error){if(!alive||token!==epoch)return;const e=safeFailure(error);fault.value=e;if([401,403,404].includes(e.status)){const oldId=session.value?.sessionId||resumeId;session.value=null;pending.value=null;if(e.status!==401)clearHint();else resumeId=oldId}else if(e.status===409){pending.value=null}else if(!e.retryable){pending.value=null}}finally{if(alive&&token===epoch){busy.value=false;if(fault.value?.status===409&&session.value)refresh()}}}
function start(){if(busy.value||pending.value)return;const language=locale.value,key=crypto.randomUUID();epoch++;session.value=null;clearHint();lastSoundRound=null;run({kind:'create',call:()=>api.create(language,key)})}
function ready(){const s=session.value;if(!s||busy.value||pending.value)return;run({kind:'ready',sessionId:s.sessionId,roundId:s.roundId,call:()=>api.ready(s.sessionId,s.roundId)})}
function answer(i){const s=session.value;if(!canAnswer.value||s.eliminated.includes(i))return;const key=crypto.randomUUID();run({kind:'answer',choice:i,sessionId:s.sessionId,roundId:s.roundId,call:()=>api.answer(s.sessionId,s.roundId,i,key)})}
function next(){const s=session.value;if(!s||busy.value||pending.value)return;run({kind:'next',sessionId:s.sessionId,roundId:s.roundId,call:()=>api.next(s.sessionId,s.roundId)})}
function fifty(){const s=session.value;if(!canAnswer.value||s.lifelineUsed)return;run({kind:'fifty',sessionId:s.sessionId,roundId:s.roundId,call:()=>api.fifty(s.sessionId,s.roundId)})}
function abandon(){const s=session.value;if(!s||busy.value)return;run({kind:'abandon',sessionId:s.sessionId,call:()=>api.abandon(s.sessionId)})}
function retry(){if(pending.value&&!busy.value)run(pending.value);else if(session.value)refresh();else if(resumeId)resume();else start()}
function resume(){if(!resumeId||busy.value)return;const id=resumeId;run({kind:'resume',sessionId:id,call:()=>api.current(id)})}
function reset(){epoch++;session.value=null;pending.value=null;fault.value=null;busy.value=false;syncing.value=false;clearHint();lastSoundRound=null}
async function refresh(){if(!session.value||busy.value||syncing.value||!alive)return;const token=epoch,id=session.value.sessionId,sent=Date.now();syncing.value=true;try{const s=await api.current(id);if(!alive||token!==epoch)return;const accepted=accept(s,id,sent);if(accepted&&commandResolved(pending.value,session.value)){pending.value=null;fault.value=null}}catch(error){if(!alive||token!==epoch)return;const e=safeFailure(error);fault.value=e;if([401,403,404].includes(e.status)){session.value=null;pending.value=null;if(e.status!==401)clearHint()}}finally{if(alive&&token===epoch)syncing.value=false}}
async function sound(){muted.value=!muted.value;try{await audio.enable(!muted.value)}catch{muted.value=true}}
function keyboard(e){if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;const i='ABCD'.indexOf(e.key.toUpperCase());if(i>=0)answer(i);else if(/^[1-4]$/.test(e.key))answer(Number(e.key)-1)}
function visibility(){audio.enable(!muted.value&&!document.hidden).catch(()=>{});if(!document.hidden)refresh()}
onMounted(()=>{reduced.value=matchMedia('(prefers-reduced-motion: reduce)').matches;try{const saved=JSON.parse(sessionStorage.getItem(KEY)||'null');if(saved&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(saved.sessionId)){resumeId=saved.sessionId;if(['en','zh-CN'].includes(saved.locale))locale.value=saved.locale;resume()}}catch{}window.addEventListener('keydown',keyboard);document.addEventListener('visibilitychange',visibility);timer=setInterval(()=>{wall.value=Date.now();if(!document.hidden&&session.value&&!['FINISHED','ABANDONED'].includes(session.value.phase)&&Date.now()-lastPoll>=1000){lastPoll=Date.now();refresh()}},100)})
onUnmounted(()=>{alive=false;epoch++;clearInterval(timer);window.removeEventListener('keydown',keyboard);document.removeEventListener('visibilitychange',visibility);audio.close()})
</script>
<template>
<div class="studio server-studio" :class="{'quiet-motion':reduced}"><div class="beam beam-left"></div><div class="beam beam-right"></div><div class="floor"></div><div class="horizon"></div>
<header class="topbar"><a class="brand" href="./index.html"><span class="brand-mark">Q<span>✦</span></span><span>环球挑战<small>QUIZ CHALLENGE</small></span></a><div class="studio-label"><span></span>SERVER MODE<em>API 1</em></div><nav><button @click="sound" :aria-pressed="!muted">{{muted?'♫ ×':'♫'}}<span class="nav-label">{{t(muted?'声音关':'声音开',muted?'SOUND OFF':'SOUND ON')}}</span></button><button @click="reduced=!reduced" :aria-pressed="reduced" :title="t('减少动画','Reduce motion')">✧</button></nav></header>
<div class="demo-ribbon server-ribbon">{{t('文字模式 · 由服务器计时与裁决 · 真实身份接入仍待完成','TEXT MODE · SERVER-AUTHORITATIVE · EXISTING IDENTITY INTEGRATION PENDING')}}</div>
<main class="main-stage">
<section v-if="fault" class="server-alert" role="alert"><strong>{{message}}</strong><small>{{fault.code}}<span v-if="fault.requestId"> · {{fault.requestId}}</span></small><div><button @click="retry" :disabled="busy">{{pending?t('重试同一请求','RETRY SAME REQUEST'):t('重新连接','RECONNECT')}}</button><button v-if="session" @click="refresh" :disabled="busy||syncing">{{t('同步服务器','SYNC SERVER')}}</button></div></section>
<section v-if="!session" class="server-entry"><div class="eyebrow">SERVER CHALLENGE · {{t('权威会话','AUTHORITATIVE SESSION')}}</div><h1>{{t('真正的挑战，','The real challenge.')}}<br><span>{{t('由服务器见证。','Verified by the server.')}}</span></h1><p class="intro">{{t('此入口不在浏览器判分，也不会模拟登录。','This entry never scores in the browser or simulates sign-in.')}}<br>{{t('现有账号、审核题包与后端就绪后，即可开局。','Start when your existing identity, approved pack and backend are ready.')}}</p><label class="server-locale">{{t('新一局语言','NEW GAME LANGUAGE')}}<select v-model="locale" :disabled="busy||!!pending"><option value="zh-CN">中文</option><option value="en">English</option></select></label><button class="start-button" @click="start" :disabled="busy||!!pending"><span>▶</span>{{busy?t('正在连接…','CONNECTING…'):t('连接并开局','CONNECT & START')}}<i>↗</i></button><p class="fine-print">{{t('原系统登录未接通时会安全拒绝，不制造游客账号','Requests are safely rejected until the original sign-in is integrated.')}}</p><a class="text-button" href="./index.html">← {{t('返回明确标注的本地演示','Back to the labeled local demo')}}</a></section>
<section v-else-if="session.phase==='FINISHED'||session.phase==='ABANDONED'" class="finale"><div class="eyebrow">{{t('服务端会话状态','SERVER SESSION STATUS')}}</div><div class="award">{{session.phase==='FINISHED'?'✦':'◌'}}</div><h1>{{session.phase==='FINISHED'?t('精彩落幕！','Challenge complete!'):t('本局已结束','Session closed')}}</h1><div class="final-score">{{session.score}}<small>/ 750</small></div><p>{{session.phase==='FINISHED'?t('完整成绩已由服务器提交','The server has committed the completed result.'):t('未完成的局不计入完整成绩','Incomplete games are not counted as completed results.')}}</p><button class="start-button" @click="reset();start()">{{t('新开一局','NEW CHALLENGE')}} ↗</button><button class="text-button" @click="reset">{{t('返回入口','Back to entry')}}</button></section>
<section v-else class="play-layout"><div class="game-bar"><button class="text-button" @click="abandon" :disabled="busy">← {{t('放弃本局','ABANDON GAME')}}</button><div class="round-dots"><span v-for="n in 5" :class="{current:n===session.roundNumber,done:n<session.roundNumber}">{{n<session.roundNumber?'✓':String(n).padStart(2,'0')}}</span></div><div class="score-label">{{t('服务器积分','SERVER SCORE')}} <strong>{{session.score}}</strong></div></div>
<div class="question-stage"><div class="question-meta"><span class="category">{{t('服务端裁决','SERVER VERIFIED')}}</span><span>ROUND {{String(session.roundNumber).padStart(2,'0')}} <i>/ 05</i></span></div><div class="question-row"><h2>{{phase==='LOADING'?t('聚光灯已就位，准备迎接下一道挑战？','The spotlight is ready. Shall we reveal your next question?'):session.question}}</h2><div class="countdown" :class="{urgent:remaining<=5&&phase==='ANSWERING',locked:phase!=='ANSWERING'}"><svg viewBox="0 0 100 100"><circle class="track" cx="50" cy="50" r="44"/><circle class="progress" cx="50" cy="50" r="44" :style="{strokeDashoffset:276.46*(1-fraction)}"/></svg><span>{{revealed?(session.reveal.awarded>0?'✓':'−'):phase==='READING'?'···':phase==='SYNCING'?'…':remaining}}<small>{{phase==='LOADING'?t('准备','READY'):t('秒','SEC')}}</small></span></div></div><div class="stage-divider"><span></span><i>✦</i><span></span></div><p class="phase-message" role="status">{{phase==='LOADING'?t('请在准备窗口结束前进入本题','Enter the question before the readiness window closes'):phase==='READING'?t('读题中，服务器窗口尚未开启','Reading. The server answer window has not opened'):phase==='SYNCING'?t('等待服务器同步结果，不在本地猜测','Waiting for the server result; no local adjudication'):t('所有时间与成绩以服务器为准','All timing and scoring are decided by the server')}}</p></div>
<div v-if="phase==='LOADING'" class="server-ready"><button class="start-button" @click="ready" :disabled="busy||!!pending">{{t('准备好了，揭开题目','READY · REVEAL QUESTION')}} →</button></div>
<div v-else class="answers"><button v-for="(option,i) in session.options" :key="session.roundId+'-'+i" @click="answer(i)" :disabled="!canAnswer||session.eliminated.includes(i)" :class="{eliminated:session.eliminated.includes(i),right:revealed&&session.reveal.correct===i,wrong:revealed&&session.reveal.selected===i&&session.reveal.awarded===0}"><span class="answer-key">{{'ABCD'[i]}}</span><span>{{session.eliminated.includes(i)?'—':option}}</span><b class="answer-status">{{revealed&&session.reveal.correct===i?'✓':revealed&&session.reveal.selected===i?'×':'↗'}}</b></button></div>
<div v-if="revealed" class="reveal" aria-live="polite"><div><span>{{`+${session.reveal.awarded} ${t('分','PTS')}`}}</span><p>{{session.reveal.explanation}}</p></div><button class="next-button" @click="next" :disabled="busy||!!pending">{{session.roundNumber===5?t('查看成绩','SEE RESULTS'):t('下一道挑战','NEXT QUESTION')}} →</button></div>
<div v-else class="lifelines"><button @click="fifty" :disabled="!canAnswer||session.lifelineUsed"><strong>50:50</strong>{{t(session.lifelineUsed?'已使用':'去掉两个错误答案',session.lifelineUsed?'USED':'REMOVE TWO')}}</button><span class="streak">{{session.streak?'✦ '+session.streak+' '+t('连胜','STREAK'):t('服务器计时不因切换页面暂停','SERVER CLOCK CONTINUES WHEN HIDDEN')}}</span><button @click="refresh" :disabled="busy||syncing">{{syncing?t('同步中…','SYNCING…'):t('同步','SYNC')}}</button></div>
<p v-if="busy" class="server-pending" role="status">{{t('正在等待服务器确认，请勿重复提交','Waiting for the server. Duplicate submissions are disabled.')}}</p></section>
</main><footer><span>QUIZ CHALLENGE <i>✦</i> {{t('登录与成绩归属由原系统和服务器确认','IDENTITY AND SCORE OWNERSHIP ARE SERVER-VERIFIED')}}</span><span>SERVER API · NO LOCAL SCORING</span></footer></div>
</template>
<style>
.server-entry{min-height:650px;padding:75px 0 65px;max-width:770px;margin:auto}.server-entry .fine-print{font-size:10px;color:#8190ac;line-height:1.8;margin:22px 0}.server-entry .text-button{display:inline-flex;align-items:center}.server-locale{display:flex;align-items:center;gap:16px;color:#b4a684;font-size:10px;letter-spacing:.1em;margin:0 0 26px}.server-locale select{min-height:43px;padding:9px 16px;border:1px solid #5d6280;background:#14203a;color:#e8d5ac}.server-alert{margin:22px auto 0;max-width:1030px;padding:17px 20px;border:1px solid #8b705555;background:#322c2966;line-height:1.7}.server-alert strong{font-size:13px;color:#e3c394;font-weight:500}.server-alert small{display:block;font-size:9px;color:#92887e;overflow-wrap:anywhere;margin:6px 0}.server-alert button{background:transparent;border:1px solid #927a53;color:#d8bc85;min-height:40px;padding:8px 15px;font-size:10px;margin-right:12px}.server-alert button:disabled{opacity:.4}.server-ribbon{color:#8b98af}.server-ready{display:flex;justify-content:center;align-items:center;min-height:173px}.server-pending{font-size:10px;text-align:center;color:#c5ad7e;margin-top:20px}.server-studio .start-button:disabled,.server-studio .next-button:disabled{opacity:.45;transform:none}.server-studio .start-button:focus-visible{outline:none;box-shadow:inset 0 0 0 3px #fff5d8}.server-studio .fine-print{color:#7b8ba9}.server-studio .finale .start-button{min-width:245px}@media(max-width:680px){.server-entry{min-height:calc(100dvh - 160px);padding:45px 0}.server-entry h1{font-size:37px}.server-alert{padding:13px;margin-top:15px}.server-alert strong{font-size:11px}.server-ready{min-height:155px}.server-ready .start-button{font-size:10px;min-width:230px}.server-locale{font-size:9px}}
</style>
