<script setup>
import {computed,nextTick,onMounted,onUnmounted,ref,shallowRef,watch} from 'vue'
import {createQuizApi,QuizApiError} from './server-api'
import {validateSnapshot,isNewer,commandResolved,validateVoiceCandidate} from './server-state'
import {createStudioAudio} from './audio'
import {createVoiceRecorder} from './voice-recorder'
import {createNarrationPlayer} from './narration'
import PlayerRecord from './PlayerRecord.vue'
import ServerStage from './ServerStage.vue'
import ChallengePicker from './ChallengePicker.vue'
import {categoryName} from './challenges'
import './style.css'
const api=createQuizApi(),audio=createStudioAudio(),KEY='quiz.server.session.v1'
const session=shallowRef(null),pending=shallowRef(null),fault=shallowRef(null),busy=ref(false),syncing=ref(false),locale=ref('zh-CN'),muted=ref(true),reduced=ref(false),wall=ref(Date.now()),offset=ref(0)
const selectedChallenge=shallowRef(null)
const recordsOpen=ref(false),pageRoot=ref(null);let recordTrigger=null,pageSuspended=false
let epoch=0,alive=true,timer,lastPoll=0,lastSoundRound=null,resumeId=null,motionQuery
const voiceState=ref('idle'),voiceConsent=ref(false),voiceCandidate=shallowRef(null),voiceChoice=ref(null),voiceFault=ref(null),voiceStarted=ref(0),voiceMax=ref(6000),voiceAttempts=ref(0)
let voiceEpoch=0,recorder=null,voiceAbort=null
const narrator=createNarrationPlayer(),narrationBusy=ref(false),narrationNotice=ref('')
const en=computed(()=>locale.value==='en'),t=(zh,enText)=>en.value?enText:zh
const projectedNow=computed(()=>wall.value+offset.value)
const phase=computed(()=>{if(!session.value)return 'IDLE';if(session.value.phase==='READING'&&projectedNow.value>=session.value.opensAt)return projectedNow.value>=session.value.deadline?'SYNCING':'ANSWERING';if(session.value.phase==='ANSWERING'&&projectedNow.value>=session.value.deadline)return'SYNCING';return session.value.phase})
const remaining=computed(()=>session.value?Math.max(0,Math.ceil(((phase.value==='LOADING'?session.value.loadingDeadline:session.value.deadline)-projectedNow.value)/1000)):0)
const fraction=computed(()=>!session.value?1:phase.value==='LOADING'||phase.value==='READING'?1:Math.max(0,Math.min(1,(session.value.deadline-projectedNow.value)/(session.value.deadline-session.value.opensAt||20000))))
const canAnswer=computed(()=>session.value&&phase.value==='ANSWERING'&&!busy.value&&!pending.value)
const revealed=computed(()=>session.value?.phase==='REVEALING')
const message=computed(()=>{const code=fault.value?.code;return ({IDENTITY_ADAPTER_NOT_CONFIGURED:t('现有登录服务尚未接入，当前安全停止开局','Existing sign-in is not connected. Starting is safely blocked.'),DISTRIBUTED_ADMISSION_NOT_CONFIGURED:t('服务端限流尚未配置，当前安全停止开局','Distributed admission is not configured. Starting is safely blocked.'),CHALLENGE_CATALOG_CHANGED:t('路线版本已更新，请重新查看路线后开局','The route version changed. Reload the reviewed routes before starting.'),CHALLENGE_UNAVAILABLE:t('这条路线当前不可用，请重新选择','This route is no longer available. Choose again.'),QUESTION_BANK_UNAVAILABLE:t('还没有满足发布条件的正式题包','No approved question pack is available.'),AUTHENTICATION_REQUIRED:t('登录已失效，请通过原系统登录后重新连接','Your sign-in expired. Sign in through the existing system, then reconnect.'),SESSION_NOT_FOUND:t('该会话不属于当前登录范围或已不可用','This session is unavailable for the current identity.'),RATE_LIMITED:t('操作较频繁，请稍后重试','Too many requests. Please try again shortly.'),NETWORK_ERROR:t('网络中断。服务器仍在计时，可重试同一请求','Connection lost. The server clock continues. Retry the same request.'),REQUEST_TIMEOUT:t('请求未及时返回。请重试同一请求或同步结果','The request timed out. Retry the same request or sync the result.'),ANSWER_DEADLINE_PASSED:t('服务器判定已超时，正在同步结果','The server deadline passed. Syncing the result.'),READY_DEADLINE_PASSED:t('准备时间已过，本局已结束','The readiness window expired. This game is closed.')})[code]||t('服务暂不可用，未在本地生成结果','Service unavailable. No result has been generated locally.')})
const voiceBusy=computed(()=>['checking','opening','recording','recognizing'].includes(voiceState.value))
const voiceCanStart=computed(()=>canAnswer.value&&voiceConsent.value&&!voiceBusy.value&&voiceAttempts.value<3&&session.value.deadline-projectedNow.value>7000)
const voiceSeconds=computed(()=>Math.min(voiceMax.value/1000,Math.max(0,(wall.value-voiceStarted.value)/1000)).toFixed(1))
const voiceMessage=computed(()=>({MIC_PERMISSION_DENIED:t('未获得麦克风许可，请直接点选答案','Microphone permission was not granted. Use the answer buttons.'),MIC_UNSUPPORTED:t('此环境不支持安全录音，请直接点选','Secure recording is unavailable here. Use the answer buttons.'),MIC_SETUP_TIMEOUT:t('麦克风准备超时，已取消本次录音','Microphone setup timed out. This recording was cancelled.'),PRIVATE_ASR_NOT_CONFIGURED:t('私有识别尚未配置，没有打开麦克风','Private recognition is not configured. The microphone was not opened.'),UNVERIFIED_SPEECH_CONTRACT:t('识别配置与隐私说明不一致，已停止','The recognition configuration does not match this privacy notice.'),AUDIO_TOO_SHORT:t('录音太短，请重新说出选项或直接点选','The recording was too short. Try again or use the buttons.'),RATE_LIMITED:t('本题语音尝试已受限，请直接点选','Voice attempts are limited. Please use the answer buttons.'),ASR_UNAVAILABLE:t('识别暂不可用，没有自动提交答案','Recognition is unavailable. No answer was submitted.'),VOICE_WINDOW_CLOSED:t('剩余时间不足，请直接选择答案','Not enough time remains. Choose an answer directly.'),INVALID_VOICE_CANDIDATE:t('候选已过期或不匹配，请直接点选','The candidate is stale or invalid. Use the answer buttons.')})[voiceFault.value]||t('录音未完成，未提交答案','Recording did not complete. No answer was submitted.'))
function cancelVoice({clearFault=true}={}){voiceEpoch++;recorder?.cancel();recorder=null;voiceAbort?.abort();voiceAbort=null;voiceState.value='idle';voiceCandidate.value=null;voiceChoice.value=null;if(clearFault)voiceFault.value=null}
function voiceCurrent(token,id,round){return alive&&token===voiceEpoch&&session.value?.sessionId===id&&session.value?.roundId===round&&phase.value==='ANSWERING'}
function voiceFailure(error,token){if(!alive||token!==voiceEpoch)return;cancelVoice();voiceFault.value=error?.code||'MIC_UNAVAILABLE';if(error?.status===429)voiceAttempts.value=3;if([401,403,404].includes(error?.status)){invalidateAccess(error)}else if(error?.status===409)refresh()}
async function startVoice(){
 if(!voiceCanStart.value)return
 cancelVoice();const token=voiceEpoch,id=session.value.sessionId,round=session.value.roundId;voiceState.value='checking'
 try{
  const caps=await api.capabilities();if(!voiceCurrent(token,id,round))return
  if(caps?.voiceCandidateConfigured!==true)throw new QuizApiError('PRIVATE_ASR_NOT_CONFIGURED',503)
  if(caps.maxAudioMillis!==6000||caps.requiresConfirmation!==true||caps.processor!=='same-host-private-asr'||caps.audioStored!==false)throw new QuizApiError('UNVERIFIED_SPEECH_CONTRACT',503)
  voiceMax.value=Math.min(6000,Math.floor(session.value.deadline-projectedNow.value-4500));if(voiceMax.value<1000)throw new QuizApiError('VOICE_WINDOW_CLOSED',409)
  voiceState.value='opening';const capture=createVoiceRecorder({maxMillis:voiceMax.value,onLimit:()=>finishVoice(token),onError:error=>voiceFailure(error,token)});recorder=capture
  await capture.start();if(!voiceCurrent(token,id,round)){capture.cancel();return}voiceStarted.value=Date.now();voiceState.value='recording'
 }catch(error){voiceFailure(error,token)}
}
async function finishVoice(token=voiceEpoch){
 if(voiceState.value!=='recording'||token!==voiceEpoch||!session.value)return
 const id=session.value.sessionId,round=session.value.roundId;let wave
 voiceState.value='recognizing'
 try{
  wave=recorder.stop();recorder=null;voiceAttempts.value++;voiceAbort=new AbortController()
  const result=await api.voice(id,round,wave,voiceAbort.signal);if(!voiceCurrent(token,id,round))return
  voiceCandidate.value=validateVoiceCandidate(result,session.value,projectedNow.value);voiceChoice.value=voiceCandidate.value.choice;voiceState.value='candidate'
 }catch(error){voiceFailure(error,token)}finally{wave?.fill(0);if(token===voiceEpoch)voiceAbort=null}
}
function confirmVoice(){const c=voiceCandidate.value,i=voiceChoice.value;if(!c||!canAnswer.value||!Number.isInteger(i)||i<0||i>3||session.value.eliminated.includes(i)||c.sessionId!==session.value.sessionId||c.roundId!==session.value.roundId||projectedNow.value>=c.expiresAt)return;cancelVoice();answer(i)}
watch(()=>[session.value?.sessionId,session.value?.roundId],(next,old)=>{if(next[0]!==old?.[0]||next[1]!==old?.[1]){narrator.cancel();narrationNotice.value='';cancelVoice();voiceAttempts.value=0}})
watch(phase,value=>{if(!['LOADING','READING'].includes(value))narrator.cancel();if(value!=='ANSWERING'&&(voiceBusy.value||voiceCandidate.value))cancelVoice()})
watch(voiceState,()=>{audio.enable(!pageSuspended&&!muted.value&&!document.hidden&&!['opening','recording'].includes(voiceState.value)).catch(()=>{muted.value=true})})
watch(voiceConsent,value=>{if(!value)cancelVoice()})
watch(()=>session.value?.eliminated?.join(','),()=>{if(voiceCandidate.value&&session.value.eliminated.includes(voiceChoice.value))cancelVoice()})
function save(s){resumeId=s.sessionId;try{sessionStorage.setItem(KEY,JSON.stringify({sessionId:s.sessionId,locale:s.locale}))}catch{}}
function clearHint(){resumeId=null;try{sessionStorage.removeItem(KEY)}catch{}}
function accept(raw,expectedId,sent){const s=validateSnapshot(raw);if(expectedId&&s.sessionId!==expectedId)throw new QuizApiError('INVALID_SESSION_SNAPSHOT',502);if(!isNewer(session.value,s))return false;session.value=s;locale.value=s.locale;offset.value=s.serverNow-(sent+Date.now())/2;wall.value=Date.now();save(s);if(s.reveal&&lastSoundRound!==s.roundId){lastSoundRound=s.roundId;audio.cue(s.reveal.awarded>0?'correct':'wrong')}return true}
function safeFailure(e){return e instanceof QuizApiError?e:new QuizApiError('NETWORK_ERROR')}
async function run(command){if(busy.value||!alive)return;const token=epoch;busy.value=true;pending.value=command;fault.value=null;const sent=Date.now();try{const data=await command.call();if(!alive||token!==epoch)return;accept(data.session||data,command.sessionId,sent);pending.value=null}catch(error){if(!alive||token!==epoch)return;const e=safeFailure(error);fault.value=e;if([401,403,404].includes(e.status)){invalidateAccess(e)}else if(e.status===409){pending.value=null}else if(!e.retryable){pending.value=null}}finally{if(alive&&token===epoch){busy.value=false;if(fault.value?.status===409&&session.value)refresh()}}}
function start(){if(busy.value||pending.value)return;recordsOpen.value=false;const language=locale.value,key=crypto.randomUUID(),challenge=selectedChallenge.value;epoch++;session.value=null;clearHint();lastSoundRound=null;run({kind:'create',call:()=>challenge?api.create(language,key,challenge):api.create(language,key)})}
async function ready(){const s=session.value;if(!s||busy.value||pending.value||narrationBusy.value)return;const token=epoch;narrationBusy.value=true;narrationNotice.value='';const armed=!muted.value&&narrator.arm(s);try{await run({kind:'ready',sessionId:s.sessionId,roundId:s.roundId,call:()=>api.ready(s.sessionId,s.roundId)});if(!alive||token!==epoch||session.value?.roundId!==s.roundId)return;const prepared=armed&&session.value.phase==='READING'&&await narrator.prepare(api,session.value);if(!alive||token!==epoch||session.value?.roundId!==s.roundId)return;if(prepared&&!pageSuspended&&!muted.value&&!document.hidden&&narrator.play(session.value,projectedNow.value)){narrationNotice.value=t('已审核旁白 · 服务器继续计时','Reviewed narration · server clock continues')}else{narrator.cancel();if(!muted.value)narrationNotice.value=t('旁白不可用或来不及完整播放，请阅读题目','Narration unavailable or too late for full playback. Read the question.')}}catch(error){if(alive&&token===epoch&&[401,403].includes(error?.status))invalidateAccess(error)}finally{if(alive&&token===epoch)narrationBusy.value=false}}
function answer(i){const s=session.value;if(!canAnswer.value||s.eliminated.includes(i))return;cancelVoice();const key=crypto.randomUUID();run({kind:'answer',choice:i,sessionId:s.sessionId,roundId:s.roundId,call:()=>api.answer(s.sessionId,s.roundId,i,key)})}
function next(){const s=session.value;if(!s||busy.value||pending.value)return;run({kind:'next',sessionId:s.sessionId,roundId:s.roundId,call:()=>api.next(s.sessionId,s.roundId)})}
function fifty(){const s=session.value;if(!canAnswer.value||s.lifelineUsed)return;run({kind:'fifty',sessionId:s.sessionId,roundId:s.roundId,call:()=>api.fifty(s.sessionId,s.roundId)})}
function abandon(){const s=session.value;if(!s||busy.value)return;run({kind:'abandon',sessionId:s.sessionId,call:()=>api.abandon(s.sessionId)})}
function retry(){if(pending.value&&!busy.value)run(pending.value);else if(session.value)refresh();else if(resumeId)resume();else start()}
function resume(){if(!resumeId||busy.value)return;const id=resumeId;return run({kind:'resume',sessionId:id,call:()=>api.current(id)})}
function reset(){selectedChallenge.value=null;recordsOpen.value=false;narrationBusy.value=false;narrator.cancel();narrationNotice.value='';cancelVoice();voiceConsent.value=false;epoch++;session.value=null;pending.value=null;fault.value=null;busy.value=false;syncing.value=false;clearHint();lastSoundRound=null}
// One boundary invalidates every old game/voice/narration callback. Reauthentication only keeps an opaque hint.
function invalidateAccess(error){const hint=session.value?.sessionId||resumeId;reset();fault.value=error;if(error.status===401&&hint)save({sessionId:hint,locale:locale.value})}
async function refresh(){if(!session.value||busy.value||syncing.value||!alive)return;const token=epoch,id=session.value.sessionId,sent=Date.now();syncing.value=true;try{const s=await api.current(id);if(!alive||token!==epoch)return;const accepted=accept(s,id,sent);if(accepted&&commandResolved(pending.value,session.value)){pending.value=null;fault.value=null}}catch(error){if(!alive||token!==epoch)return;const e=safeFailure(error);fault.value=e;if([401,403,404].includes(e.status)){invalidateAccess(e)}}finally{if(alive&&token===epoch)syncing.value=false}}
async function sound(){muted.value=!muted.value;if(muted.value)narrator.cancel();try{await audio.enable(!pageSuspended&&!muted.value&&!document.hidden&&!['opening','recording'].includes(voiceState.value))}catch{muted.value=true}}
function openRecords(event){recordTrigger=event.currentTarget;recordsOpen.value=true}
async function closeRecords(){recordsOpen.value=false;await nextTick();if(recordTrigger?.isConnected)recordTrigger.focus()}
function recordExpired(error){if(!recordsOpen.value)return;reset();fault.value=error}
function keyboard(e){if(e.key==='Escape'){cancelVoice();return}if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;const i='ABCD'.indexOf(e.key.toUpperCase());if(i>=0)answer(i);else if(/^[1-4]$/.test(e.key))answer(Number(e.key)-1)}
function hidePage(){const hint=session.value?.sessionId||resumeId;reset();if(hint)save({sessionId:hint,locale:locale.value});pageSuspended=true;if(pageRoot.value)pageRoot.value.hidden=true;audio.enable(false).catch(()=>{})}
async function restorePage(){if(!alive||!pageSuspended||document.hidden)return;const token=epoch;pageSuspended=false;await nextTick();if(!alive||token!==epoch)return;if(document.hidden){pageSuspended=true;return}if(pageRoot.value)pageRoot.value.hidden=false;if(resumeId)await resume();if(alive&&token===epoch&&!document.hidden)audio.enable(!muted.value).catch(()=>{})}
function showPage(event){if(!event.persisted&&!pageSuspended)return;if(!pageSuspended)hidePage();restorePage()}
function visibility(){if(document.hidden){cancelVoice();narrator.cancel();}audio.enable(!pageSuspended&&!muted.value&&!document.hidden&&!['opening','recording'].includes(voiceState.value)).catch(()=>{});if(!document.hidden){if(pageSuspended)restorePage();else refresh()}}

function motionPreference(event){reduced.value=event.matches}
onMounted(()=>{motionQuery=matchMedia('(prefers-reduced-motion: reduce)');reduced.value=motionQuery.matches;motionQuery.addEventListener?.('change',motionPreference);try{const saved=JSON.parse(sessionStorage.getItem(KEY)||'null');if(saved&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(saved.sessionId)){resumeId=saved.sessionId;if(['en','zh-CN'].includes(saved.locale))locale.value=saved.locale;resume()}}catch{}window.addEventListener('keydown',keyboard);window.addEventListener('pagehide',hidePage);window.addEventListener('pageshow',showPage);document.addEventListener('visibilitychange',visibility);timer=setInterval(()=>{wall.value=Date.now();if(!document.hidden&&session.value&&!['FINISHED','ABANDONED'].includes(session.value.phase)&&Date.now()-lastPoll>=1000){lastPoll=Date.now();refresh()}},100)})
onUnmounted(()=>{motionQuery?.removeEventListener?.('change',motionPreference);alive=false;narrator.cancel();cancelVoice();epoch++;clearInterval(timer);window.removeEventListener('keydown',keyboard);window.removeEventListener('pagehide',hidePage);window.removeEventListener('pageshow',showPage);document.removeEventListener('visibilitychange',visibility);audio.close()})
</script>
<template>
<div ref="pageRoot" class="studio server-studio" :class="{'quiet-motion':reduced}"><ServerStage :phase="phase" :round-key="session?session.sessionId+':'+session.roundId:''" :outcome="revealed?(session.reveal.awarded>0?'correct':'learn'):''" :reduced="reduced"/><div class="beam beam-left"></div><div class="beam beam-right"></div><div class="floor"></div><div class="horizon"></div>
<header class="topbar"><a class="brand" href="./index.html"><span class="brand-mark">Q<span>✦</span></span><span>环球挑战<small>QUIZ CHALLENGE</small></span></a><div class="studio-label"><span></span>SERVER MODE<em>API 1</em></div><nav><button @click="sound" :aria-pressed="!muted">{{muted?'♫ ×':'♫'}}<span class="nav-label">{{t(muted?'声音关':'声音开',muted?'SOUND OFF':'SOUND ON')}}</span></button><button @click="reduced=!reduced" :aria-pressed="reduced" :title="t('减少动画','Reduce motion')">✧</button></nav></header>
<div class="demo-ribbon server-ribbon">{{t('服务器裁决 · 语音仍需确认 · 真实身份接入仍待完成','SERVER AUTHORITY · VOICE REQUIRES CONFIRMATION · IDENTITY INTEGRATION PENDING')}}</div>
<main class="main-stage">
<section v-if="fault" class="server-alert" role="alert"><strong>{{message}}</strong><small>{{fault.code}}<span v-if="fault.requestId"> · {{fault.requestId}}</span></small><div><button @click="retry" :disabled="busy">{{pending?t('重试同一请求','RETRY SAME REQUEST'):t('重新连接','RECONNECT')}}</button><button v-if="session" @click="refresh" :disabled="busy||syncing">{{t('同步服务器','SYNC SERVER')}}</button></div></section>
<section v-if="!session" class="server-entry"><div class="eyebrow">SERVER CHALLENGE · {{t('权威会话','AUTHORITATIVE SESSION')}}</div><h1>{{t('真正的挑战，','The real challenge.')}}<br><span>{{t('由服务器见证。','Verified by the server.')}}</span></h1><p class="intro">{{t('此入口不在浏览器判分，也不会模拟登录。','This entry never scores in the browser or simulates sign-in.')}}<br>{{t('现有账号、审核题包与后端就绪后，即可开局。','Start when your existing identity, approved pack and backend are ready.')}}</p><label class="server-locale">{{t('新一局语言','NEW GAME LANGUAGE')}}<select v-model="locale" :disabled="busy||!!pending"><option value="zh-CN">中文</option><option value="en">English</option></select></label><ChallengePicker :api="api" :locale="locale" :disabled="busy||!!pending" @choose="selectedChallenge=$event" @expired="invalidateAccess"/><button class="start-button" @click="start" :disabled="busy||!!pending"><span>▶</span>{{busy?t('正在连接…','CONNECTING…'):t('连接并开局','CONNECT & START')}}<i>↗</i></button><p class="fine-print">{{t('原系统登录未接通时会安全拒绝，不制造游客账号','Requests are safely rejected until the original sign-in is integrated.')}}</p><button class="text-button record-open" @click="openRecords" :disabled="busy||!!pending" :aria-expanded="recordsOpen">{{t('查看我的战绩','VIEW MY RECORD')}}</button><a class="text-button" href="./index.html">← {{t('返回明确标注的本地演示','Back to the labeled local demo')}}</a></section>
<section v-else-if="session.phase==='FINISHED'||session.phase==='ABANDONED'" class="finale"><div class="eyebrow">{{t('服务端会话状态','SERVER SESSION STATUS')}}</div><div class="award">{{session.phase==='FINISHED'?'✦':'◌'}}</div><h1>{{session.phase==='FINISHED'?t('精彩落幕！','Challenge complete!'):t('本局已结束','Session closed')}}</h1><div class="final-score">{{session.score}}<small>/ 750</small></div><p>{{session.phase==='FINISHED'?t('完整成绩已由服务器提交','The server has committed the completed result.'):t('未完成的局不计入完整成绩','Incomplete games are not counted as completed results.')}}</p><button class="start-button" @click="reset();start()">{{t('新开一局','NEW CHALLENGE')}} ↗</button><button class="text-button record-open" @click="openRecords" :aria-expanded="recordsOpen">{{t('查看我的战绩','VIEW MY RECORD')}}</button><button class="text-button" @click="reset">{{t('返回入口','Back to entry')}}</button></section>
<section v-else class="play-layout"><div class="game-bar"><button class="text-button" @click="abandon" :disabled="busy">← {{t('放弃本局','ABANDON GAME')}}</button><div class="round-dots"><span v-for="n in 5" :class="{current:n===session.roundNumber,done:n<session.roundNumber}">{{n<session.roundNumber?'✓':String(n).padStart(2,'0')}}</span></div><div class="score-label">{{t('服务器积分','SERVER SCORE')}} <strong>{{session.score}}</strong></div></div>
<div class="question-stage"><div class="question-meta"><span class="category">{{session.challenge?session.challenge.title:t('服务端裁决','SERVER VERIFIED')}}</span><span>ROUND {{String(session.roundNumber).padStart(2,'0')}} <i>/ 05</i></span></div><p v-if="session.challenge" class="challenge-note">{{categoryName(session.challenge.slots[session.roundNumber-1].category,en)}} · {{t('难度','DIFFICULTY')}} {{session.challenge.slots[session.roundNumber-1].difficulty}} / 3</p><div class="question-row"><h2>{{phase==='LOADING'?t('聚光灯已就位，准备迎接下一道挑战？','The spotlight is ready. Shall we reveal your next question?'):session.question}}</h2><div class="countdown" :class="{urgent:remaining<=5&&phase==='ANSWERING',locked:phase!=='ANSWERING'}"><svg viewBox="0 0 100 100"><circle class="track" cx="50" cy="50" r="44"/><circle class="progress" cx="50" cy="50" r="44" :style="{strokeDashoffset:276.46*(1-fraction)}"/></svg><span>{{revealed?(session.reveal.awarded>0?'✓':'−'):phase==='READING'?'···':phase==='SYNCING'?'…':remaining}}<small>{{phase==='LOADING'?t('准备','READY'):t('秒','SEC')}}</small></span></div></div><div class="stage-divider"><span></span><i>✦</i><span></span></div><p class="phase-message" role="status">{{phase==='LOADING'?t('请在准备窗口结束前进入本题','Enter the question before the readiness window closes'):phase==='READING'?t('读题中，服务器窗口尚未开启','Reading. The server answer window has not opened'):phase==='SYNCING'?t('等待服务器同步结果，不在本地猜测','Waiting for the server result; no local adjudication'):t('所有时间与成绩以服务器为准','All timing and scoring are decided by the server')}}</p></div>
<div v-if="phase==='LOADING'" class="server-ready"><button class="start-button" @click="ready" :disabled="busy||!!pending||narrationBusy">{{t('准备好了，揭开题目','READY · REVEAL QUESTION')}} →</button></div>
<div v-else class="answers"><button v-for="(option,i) in session.options" :key="session.roundId+'-'+i" @click="answer(i)" :disabled="!canAnswer||session.eliminated.includes(i)" :class="{eliminated:session.eliminated.includes(i),right:revealed&&session.reveal.correct===i,wrong:revealed&&session.reveal.selected===i&&session.reveal.awarded===0}"><span class="answer-key">{{'ABCD'[i]}}</span><span>{{session.eliminated.includes(i)?'—':option}}</span><b class="answer-status">{{revealed&&session.reveal.correct===i?'✓':revealed&&session.reveal.selected===i?'×':'↗'}}</b></button></div>
<div v-if="revealed" class="reveal" aria-live="polite"><div><span>{{`+${session.reveal.awarded} ${t('分','PTS')}`}}</span><p>{{session.reveal.explanation}}</p></div><button class="next-button" @click="next" :disabled="busy||!!pending">{{session.roundNumber===5?t('查看成绩','SEE RESULTS'):t('下一道挑战','NEXT QUESTION')}} →</button></div>
<div v-else class="lifelines"><button @click="fifty" :disabled="!canAnswer||session.lifelineUsed"><strong>50:50</strong>{{t(session.lifelineUsed?'已使用':'去掉两个错误答案',session.lifelineUsed?'USED':'REMOVE TWO')}}</button><span class="streak">{{session.streak?'✦ '+session.streak+' '+t('连胜','STREAK'):t('服务器计时不因切换页面暂停','SERVER CLOCK CONTINUES WHEN HIDDEN')}}</span><button @click="refresh" :disabled="busy||syncing">{{syncing?t('同步中…','SYNCING…'):t('同步','SYNC')}}</button></div>
<section class="voice-panel" v-if="!revealed&&phase!=='LOADING'" aria-label="语音候选">
 <div class="voice-heading"><strong>◉ {{t('语音候选','VOICE CANDIDATE')}}</strong><span>{{t('不自动作答 · 每题最多3次','NEVER AUTO-SUBMITS · UP TO 3 ATTEMPTS')}}</span></div>
 <label class="voice-consent"><input type="checkbox" v-model="voiceConsent"/>{{t('我同意将本次录音发送到同源游戏服务器，由服务主机上的私有模型识别；本服务不持久保存录音','I agree to send this recording to the same-origin game server for its private model to transcribe; this service does not persist recordings')}}</label>
 <p class="voice-notice">{{t('最长6秒，到时自动发送识别；倒计时不暂停。识别仅给候选，仍需确认；答题窗口内也可点击或用键盘','Up to 6 seconds, then sent for recognition; the game clock continues. You must confirm the candidate. Buttons and keyboard remain options during the answer window.')}}</p>
 <div class="voice-controls"><button class="voice-start" @click="startVoice" :disabled="!voiceCanStart">{{t('按下开始录音','START RECORDING')}}</button><button v-if="voiceState==='recording'" class="voice-stop" @click="finishVoice()">■ {{t('结束并识别','STOP & TRANSCRIBE')}}</button><button v-if="voiceBusy||voiceCandidate" class="voice-cancel" @click="cancelVoice()">{{t('取消 / Esc','CANCEL / ESC')}}</button><span class="voice-recording" v-if="voiceState==='recording'" aria-hidden="true">● {{voiceSeconds}} / {{voiceMax/1000}}s</span></div>
 <p v-if="voiceBusy" class="voice-status" role="status">{{voiceState==='checking'?t('正在核对服务与隐私配置…','Checking the service and privacy configuration…'):voiceState==='opening'?t('等待麦克风许可，尚未上传录音…','Waiting for microphone permission; no recording uploaded…'):voiceState==='recording'?t('正在录音，说出选项字母或完整选项','Recording. Say the option letter or full option'):t('正在等待识别候选，未提交答案…','Waiting for a candidate. No answer has been submitted…')}}</p>
 <p v-if="voiceFault" class="voice-error" role="alert">{{voiceMessage}}</p>
 <div v-if="voiceCandidate" class="voice-result"><p>{{t('识别文字：','Heard: ')}}<span>{{voiceCandidate.transcript||t('没有明确文字','No clear speech')}}</span></p><label>{{t('请核对并选择','CHECK THE CHOICE')}}<select v-model.number="voiceChoice"><option :value="null" disabled>{{t('未明确，请选择','No clear choice; select one')}}</option><option v-for="(option,i) in session.options" :key="i" :value="i" :disabled="session.eliminated.includes(i)">{{'ABCD'[i]}} · {{option}}</option></select></label><button class="voice-confirm" @click="confirmVoice" :disabled="!canAnswer||voiceChoice===null||session.eliminated.includes(voiceChoice)">{{t('确认提交此答案','CONFIRM & SUBMIT ANSWER')}} →</button><small>{{t('确认前不会计分；你也可以直接点击上方答案','No scoring before confirmation. You can also choose a button above.')}}</small></div>
</section>
<p v-if="narrationBusy" class="server-pending" role="status">{{t('正在加载本题旁白，服务器继续计时','Loading this question’s narration. The server clock continues.')}}</p><p v-if="narrationNotice" class="server-pending" role="status">{{narrationNotice}}</p><p v-if="busy" class="server-pending" role="status">{{t('正在等待服务器确认，请勿重复提交','Waiting for the server. Duplicate submissions are disabled.')}}</p></section>
<PlayerRecord v-if="recordsOpen&&(!session||['FINISHED','ABANDONED'].includes(session.phase))" :api="api" :locale="locale" @close="closeRecords" @expired="recordExpired"/>
</main><footer><span>QUIZ CHALLENGE <i>✦</i> {{t('登录与成绩归属由原系统和服务器确认','IDENTITY AND SCORE OWNERSHIP ARE SERVER-VERIFIED')}}</span><span>SERVER API · NO LOCAL SCORING</span></footer></div>
</template>
<style>
.server-studio[hidden]{display:none!important}

.record-open{display:block;min-height:44px;margin:20px 0}.finale .record-open{margin:20px auto}

.server-entry{min-height:650px;padding:75px 0 65px;max-width:770px;margin:auto}.server-entry .fine-print{font-size:10px;color:#8190ac;line-height:1.8;margin:22px 0}.server-entry .text-button{display:inline-flex;align-items:center}.server-locale{display:flex;align-items:center;gap:16px;color:#b4a684;font-size:10px;letter-spacing:.1em;margin:0 0 26px}.server-locale select{min-height:43px;padding:9px 16px;border:1px solid #5d6280;background:#14203a;color:#e8d5ac}.server-alert{margin:22px auto 0;max-width:1030px;padding:17px 20px;border:1px solid #8b705555;background:#322c2966;line-height:1.7}.server-alert strong{font-size:13px;color:#e3c394;font-weight:500}.server-alert small{display:block;font-size:9px;color:#92887e;overflow-wrap:anywhere;margin:6px 0}.server-alert button{background:transparent;border:1px solid #927a53;color:#d8bc85;min-height:40px;padding:8px 15px;font-size:10px;margin-right:12px}.server-alert button:disabled{opacity:.4}.server-ribbon{color:#8b98af}.server-ready{display:flex;justify-content:center;align-items:center;min-height:173px}.server-pending{font-size:10px;text-align:center;color:#c5ad7e;margin-top:20px}.server-studio .start-button:disabled,.server-studio .next-button:disabled{opacity:.45;transform:none}.server-studio .start-button:focus-visible{outline:none;box-shadow:inset 0 0 0 3px #fff5d8}.server-studio .fine-print{color:#7b8ba9}.server-studio .finale .start-button{min-width:245px}@media(max-width:680px){.server-entry{min-height:calc(100dvh - 160px);padding:45px 0}.server-entry h1{font-size:37px}.server-alert{padding:13px;margin-top:15px}.server-alert strong{font-size:11px}.server-ready{min-height:155px}.server-ready .start-button{font-size:10px;min-width:230px}.server-locale{font-size:9px}}
.voice-panel{margin:18px 0 0;padding:18px 22px;border-top:1px solid #c2a26255;background:linear-gradient(100deg,#aa863611,#101e3644);color:#9eacc5}.voice-heading{display:flex;justify-content:space-between;gap:14px;margin-bottom:13px}.voice-heading strong{color:#c7ae7c;font-size:11px;letter-spacing:.16em}.voice-heading>span{font-size:8px;letter-spacing:.08em;color:#728099}.voice-consent{display:flex;gap:10px;align-items:flex-start;font-size:10px;line-height:1.7;cursor:pointer}.voice-consent input{margin:3px 0 0;accent-color:#c7ae7c;flex:0 0 auto}.voice-notice{font-size:9px;line-height:1.6;color:#7889a5;margin:9px 0 13px}.voice-controls{display:flex;flex-wrap:wrap;align-items:center;gap:9px}.voice-panel button{min-height:39px;background:#111d31;border:1px solid #b99a5b70;color:#d5bb86;padding:9px 14px;font-size:9px;letter-spacing:.05em;cursor:pointer}.voice-panel button:disabled{opacity:.35;cursor:not-allowed}.voice-panel button:focus-visible,.voice-panel select:focus-visible{outline:2px solid #ffe0a0;outline-offset:3px}.voice-recording{color:#f0a080;font-size:10px;font-variant-numeric:tabular-nums}.voice-status,.voice-error{font-size:10px;line-height:1.7;margin:13px 0 0}.voice-error{color:#dcb07e}.voice-result{margin-top:16px;padding-top:14px;border-top:1px solid #bd9e5c33}.voice-result p{font-size:11px;line-height:1.6;overflow-wrap:anywhere}.voice-result p span{color:#ead7b0}.voice-result label{display:flex;align-items:center;gap:12px;font-size:9px;margin:12px 0}.voice-result select{min-height:42px;max-width:70%;background:#15213a;border:1px solid #846d45;color:#dfc89e;padding:8px}.voice-result small{display:block;font-size:8px;margin-top:10px;color:#7c8ca6}@media(max-width:680px){.voice-panel{padding:15px 12px}.voice-heading{display:block}.voice-heading>span{display:block;margin-top:8px}.voice-result label{display:block}.voice-result select{display:block;max-width:100%;width:100%;margin-top:8px}.voice-panel button{font-size:8px;padding:8px 10px}}
</style>
